### PR TITLE
Remove core predicate functions

### PR DESCRIPTION
**Pull request by Kodiologist**
I wasn't sure which of these to delete and which to move to the spin-off library. It's one of those things where it's hard to draw the line between useful syntactic sugar and an endless parade of tiny functions. Ultimately I just decided to trash all of them.

### CODE REVIEW

**Comment by allison-casey** [comment]
probably for the best

**Review by allison-casey — APPROVED** [review]

**Comment by Kodiologist** [comment]
After sleeping on it, I think `some` should also be deleted, and `coll?`, being nontrivial and surprisingly useful, is worth keeping for the spin-off library. I'll remove some uses of `coll?` but keep it in Hy until the spin-off library exists. Does that still sound good, Allie?

**Comment by allison-casey** [comment]
i would say generally err on the side of getting rid of trivial things. `some` is just a slightly more obtuse `any` whose alternative case is better served by `ap-first` anyways. In that spirit i'd say `coll?` is nontrivial enough, and relevant enough to Hy's functional style, to merit keeping for now. We can always add some of these things back in later if there's demand enough.

**Comment by Kodiologist** [comment]
Yeah, the reason I wouldn't see myself using `some` is its use of a predicate function. I would more often want something like `(next (gfor …))`.

**Comment by Kodiologist** [comment]
Done. I also made an unrelated fix to `conftest.py` in the first commit.

**Review by scauligi — APPROVED** [review]
You can use `(not expr)` in place of `(= expr 0)` as a slightly more terse replacement for `(zero? expr)`, but not a major thing.
Otherwise looks fine to me.

Many of these will reappear in the eventual standard library, yeah?

**Comment by Kodiologist** [comment]
Yeah, I figured `(= x 0)` was a bit more explicit, which was the only reason to use `zero?` in place of `not` in most cases.

> Many of these will reappear in the eventual standard library, yeah?

The proposal here is that only `coll?` will. If you want to keep any of the others, now's the time to object.

**Comment by scauligi** [comment]
> Yeah, I figured (= x 0) was a bit more explicit

Reasonable!

> If you want to keep any of the others...

Hmm, I think it can be useful to have the various helper predicates in the (separate) stdlib, since they seem like they'd be common enough that users would be redefining them anyway (e.g. the `zero?` predicate vs using `(fn [x] (= x 0))` every time)

**Comment by Kodiologist** [comment]
Yeah, but I'm asking, which ones? All of them? Speaking for myself, I get little to no use out of these because I use comprehension forms or anaphoric macros in place of higher-order functions. They're more flexible; they're reasonably concise even if you don't already have the exact mapping function or predicate function or whatever that you need. Using higher-order functions is more concise in Haskell, but that's because Haskell makes it easy to make complex compositions of functions on the fly, so again you don't need to rely on a large preexisting library.

**Comment by scauligi** [comment]
> I use comprehension forms or anaphoric macros in place of higher-order functions.

Hmm fair enough, I haven't tried using the anaphoric macros yet but I can see how they could replace needing the different predicates.

**Pull request merged**
