### PR TITLE
Add `#/` import reader macro

### PR DESCRIPTION
**Pull request by scauligi**
Reader macro `#/` for accessing `hy.M` import helper.
Examples:
```hy
(#/re.match r"re(gex)?" line)
(= (type #/collections/abc #/types.ModuleType))
(print #/os/path.curdir)
```

### CODE REVIEW

**Comment by scauligi** [comment]
Ah should have submitted this as a draft for now, it depends on https://github.com/hylang/hy/pull/2425

**Review by scauligi — COMMENTED** [review]
> Pull request authors can't request changes on their own pull request


Well that's just silly.

---

Anyways @scauligi, speaking as a maintainer, you need to wait until #2425 lands.
Once it does, rebase your commits and add a line to `NEWS.rst`. After that we'll take a look at your PR.

**Comment by Kodiologist** [comment]
Your comment made me giggle.

I like this syntax, but do you think this should be in Hyrule rather than Hy? Since it's a reader macro, it's easy to use in a quasiquoted construct without having to import or require or whatever in the expansion, so being in Hyrule shouldn't keep it from being convenient.

**Comment by Kodiologist** [comment]
And that would allow users to use the rather desirable reader-macro name `/` for something else if they desire.

**Comment by Kodiologist** [comment]
Also, before I forget: it's probably better to write examples with a space after the reader macro name, e.g. `#/ collections/abc`. `/` is an identifier character, so in order to get more consistent behavior in parsing reader-macro calls, I'd like to eventually get `#/collections/abc` to unconditionally attempt to call a reader macro named `/collections/abc`. See our conversation in #2306.

**Pull request closed without merging**
