### PR TITLE
Implement PEP 3107 & 526 annotations

### PR DESCRIPTION
**Pull request by refi64**
Ref. #1794. I'm going to split this up into more commits (partly since I ended up majorly reworking the function argument parsing code) but figured I should get the initial WIP out there for a basic overview. The syntax used is identical to the accepted proposal in #1794.

### CODE REVIEW

**Comment by Kodiologist** [comment]
`model[0] == HySymbol("annotate*")` — Careful, this will trigger on a string literal. You need to check that `model[0]` is a symbol.

**Comment by refi64** [comment]
Oof, will change with the next push.

**Comment by Kodiologist** [comment]
Is this ready for review, then?

**Comment by refi64** [comment]
Was just typing out that it was indeed ready for review and then got distracted force-pushing a local tweak. :sweat_smile: 

So yeah, AFAIK this should be good to go, all tests pass locally.

**Comment by refi64** [comment]
Okay so I've resolved most of this and am working on docs now (will probably finish tomorrow).

> Design-wise, it seems a bit odd to me that for function parameters with default values, the annotation is put inside the square brackets, whereas there are no square brackets for other parameters. `Does (defn f [^int p1 p2 ^str p3 &optional ^str o1 ^int [o2 0]] …)` look too weird to you?

I'm indifferent tbh, I followed that syntax because it's what was originally proposed in #1794. That being said, one con of changing it would be that you have items relating to the argument being defined inside *and* outside the brackets.

**Comment by Kodiologist** [comment]
Don't forget about this, my dude. You've had several great PRs that floundered near the end and didn't make it in.

**Comment by Kodiologist** [comment]
Also, I would vote for putting the annotation outside the brackets for default arguments.

**Comment by refi64** [comment]
I swear this will be done on Monday at the latest...

**Comment by refi64** [comment]
I think I covered everything and also added the `of` macro discussed in the same issue & docs.

**Comment by Kodiologist** [comment]
All looks good except that:

- The trailing-whitespace fix for `tutorial.rst` shouldn't be in the compiler commit. Put it in its own commit if you want it in this PR.
- Is `whitelisted_roots` left in by mistake?
- I'd argue against including annotations in the tutorial, which should be short and cover only the basics.
- In the reference documentation for annotations, you may want to add some links to the Python documentation that describes their semantics.

**Comment by refi64** [comment]
Done.

**Comment by Kodiologist** [comment]
It looks like 806b04a adds some trailing space that's then removed in the next commit. Try `git log --stat`.

**Pull request merged**
