### PR TITLE
Use license headers consistently

### LINKED ISSUE #1225: Policy for copyright and license notices at the start of each file
[GNU recommends these](https://www.gnu.org/licenses/gpl-howto.html) when you're using the GPL. However, I doubt they're necessary (we have a LICENSE file), and they add a lot of noise to files, especially small files. In any case, if we decide they should stay, they should probably be in every file, and we need a policy for exactly which people and years get credited in each file, whereas right now they're inconsistent.

- Thumbs-up this issue if you think the notices should be removed.
- Thumbs-down this issue if you think they should stay and be used consistently.

@paultag, could you provide your input?

### PR DESCRIPTION
**Pull request by Kodiologist**
Closes #1225.

### CODE REVIEW

**Comment by Kodiologist** [comment]
@tuturto @kirbyfan64 Let's get this moving if possible, because it touches so many files that merge conflicts are inevitable with any other PRs.

**Comment by tuturto** [comment]
Yeah, I'll try to tackle this soon. Having plenty of things on my plate currently. In the meantime, @paultag any comments?

**Comment by theanalyst** [comment]
@paultag are we actually supposed to remove the copyright of the previous years as well? (ofc, IANAL)

**Comment by Kodiologist** [comment]
@kirbyfan64 Poke.

**Comment by gilch** [comment]
Disclaimer: I am not a lawyer. I probably don't know what I'm talking about. Neither are the other authors. This seems to be the reason we're not getting much participation on this issue. It's holding us up though.

Copyright declarations can help avoid confusion about ownership, but are not actually legally required in the United States at the moment. The copyright automatically applies as soon as the work is written down. I don't know about the laws elsewhere.

I don't think it matters if an individual file is conceivably copyrightable. The copyright and license applies to Hy as a whole, rather than its individual files. And the license itself doesn't appear to require headers at all.

The Git repository tracks authorship and dates well enough for legal purposes, but the headers should not contradict this (and they do at the moment). I'm inclined to approve this pull as an improvement to the status quo. If anyone has strong objections, afterwards make another pull I guess.

**Comment by Kodiologist** [comment]
Thanks!

**Pull request merged**
