### PR TITLE
Allow 'for' and 'cond' to take a multi-expression body

### PR DESCRIPTION
**Pull request by kirbyfan64**
I also fixed a slight docstring slip-up. Ref. #868.

### CODE REVIEW

**Comment by algernon** [comment]
[tests/native_tests/contrib/walk.hy](https://github.com/kirbyfan64/hy/blob/fc05f5a6c6bb23316732f59b34c9657367b156f0/tests/native_tests/contrib/walk.hy#L35) needs an update, for the implicit do.

Other than that, looks good! :+1: after the test fix.

**Comment by kirbyfan64** [comment]
Ack, I skewered my history again. Hold on...

**Comment by kirbyfan64** [comment]
All fixed!

**Comment by gilch** [comment]
How is the `else` clause supposed to work in the new `for`? I can't get it to work.
Current:
```Hy
=> (for [x (range 3)] None (else (print "done")))
from hy.core.language import range
for x in range(3):
    None
else:
    print('done')
done
```
Proposed:
```Hy
=> (for [x (range 3)] None (else (print "done")))
from hy.core.language import range
for x in range(3):
    None
    else(print('done'))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'else' is not defined
```

**Comment by kirbyfan64** [comment]
@gilch Fixed.

**Comment by algernon** [comment]
There's a failing test... something changed in a way the test doesn't like. Probably harmless, but should be investigated. Do you want to do it @kirbyfan64, or shall I have a go at it?

**Comment by algernon** [comment]
I had a go at it: `(get [] -1)` raised an error, that was the bulk of it. And that came to be because in `(for [x])`, we have no body. So adding a check before the `(setv lst (get body -1))` fixes the issue. The check should throw a "requires body to evaluate" error, and we'll keep the other check within the cond too, to catch the case where there is an else-body only.

I'll add these changes to a branch, with a test case, and merge that along with the changes in this PR.

**Pull request closed without merging**
