### PR TITLE
Interactive Shell Enhancement

### PR DESCRIPTION
**Pull request by digitalvectorz**
Added readline to support use of arrow keys and tab completion

### CODE REVIEW

**Comment by paultag** [comment]
@digitalvectorz don't we already have tab complete? (https://github.com/hylang/hy/blob/master/hy/completer.py#L50-L53)

**Comment by digitalvectorz** [comment]
We had an issue with using the up and down arrows to recall previous
commands...the tab complete was a consequence of fixing that

Johnathon Mlady
[GoogleVoice] 440.782.1dvz (1389)

**Comment by paultag** [comment]
@digitalvectorz What platform and conditions?

**Comment by paultag** [comment]
(We import readline over in https://github.com/hylang/hy/blob/master/hy/completer.py#L40-L48 too)

**Comment by digitalvectorz** [comment]
Ubuntu 12.04  python 3.5 virtual env...fresh install.

Johnathon Mlady
[GoogleVoice] 440.782.1dvz (1389)

**Comment by paultag** [comment]
@digitalvectorz I can't reproduce - and on and older version -- http://asciinema.org/a/89notjhpgljyt390qe6tpx9f7

How are you launching hy? Can you send me a screengrab?

**Comment by digitalvectorz** [comment]
When I get to the computer I will...

Launching with just hy from command line

Johnathon Mlady
[GoogleVoice] 440.782.1dvz (1389)

**Comment by paultag** [comment]
@digitalvectorz any update?

**Comment by Kodiologist** [comment]
Since nobody's been able to reproduce this bug, I think this PR can be closed.

**Pull request closed without merging**
