### PR TITLE
Improve note about `defmacro` parameters in the API docs

### PR DESCRIPTION
**Pull request by wrobell**

### CODE REVIEW

**Comment by Kodiologist** [comment]
I'm not sure this is an improvement. "All values are passed to macros unevaluated, therefore ``defmacro`` cannot use keyword arguments, or kwargs." feels like a comma splice.

**Comment by wrobell** [comment]
Let's remove the ", or kwargs" part as well?

**Comment by Kodiologist** [comment]
The comma that should perhaps be a different punctuation mark is the earlier one. "All values are passed to macros unevaluated" and "therefore `defmacro` cannot use keyword arguments, or kwargs" are independent clauses. The original text avoids this by using "because" instead of "therefore". So yeah, I don't see how this change is an improvement.

**Comment by wrobell** [comment]
Just trying to correct the lowercase letter at the start of the sentence and make it simpler.

Originally
```
because all values are passed to macros unevaluated,
defmacro cannot use keyword arguments, or kwargs.
All arguments are passed in positionally.
Parameters can still be given default values however::
...
```

At the moment in the pull request
```
All values are passed to macros unevaluated,
therefore defmacro cannot use keyword arguments, or kwargs.
All arguments are passed positionally,
but they can have default values::
...
```

If you don't mind, considering your feedback, I would propose then
```
Because all values are passed to macros unevaluated,
defmacro cannot use keyword arguments, or kwargs.
All arguments are passed positionally,
but they can have default values::
...
```
or
```
defmacro cannot use keyword arguments,
because all values are passed to macros unevaluated.
All arguments are passed positionally,
but they can have default values::
...
```

**Comment by Kodiologist** [comment]
Let's go with the last one. Anyway, this is one of the core macros for which I'll have to eventually overhaul the documentation.

**Comment by wrobell** [comment]
@Kodiologist See commit 940e6b7.

**Comment by Kodiologist** [comment]
Thanks.

**Comment by goyalyashpal** [comment]
hey @Kodiologist just wondering is there any reason for not using "rebase and merge" ?

**Comment by Kodiologist** [comment]
Doing that removes the PR's history as a separate branch in the Git history. It's as if all the PR commits were pushed directly to `master`.

**Comment by goyalyashpal** [comment]
> Doing that removes the PR's history as a separate branch in the Git history.
> you can see the branching structure with e.g. `git log --oneline --graph`.

<details><summary>Console output</summary>

```console
$ git log --oneline --graph --no-decorate
*   d0b76948 Merge pull request #2482 from wrobell/fix-def-macro-note
|\  
| * ae93d3ad Improve note about `defmacro` parameters in the API docs
|/  
*   899aa00a Merge pull request #2477 from Kodiologist/onedot-macro-calls
|\  
| * 5cf300ac Correct `root` in pattern macros with dotted head
|/  
*   b105027c Merge pull request #2479 from scauligi/f-quotes
|\  
| * 48c44d61 update error message in prior test
| * 4dabf691 Convert strings ourselves instead of using `eval`
|/  
*   2d6d5f9c Merge pull request #2471 from Kodiologist/pattern-errs
```

```console
$ git log --oneline --no-decorate
d0b76948 Merge pull request #2482 from wrobell/fix-def-macro-note
ae93d3ad Improve note about `defmacro` parameters in the API docs
899aa00a Merge pull request #2477 from Kodiologist/onedot-macro-calls
5cf300ac Correct `root` in pattern macros with dotted head
b105027c Merge pull request #2479 from scauligi/f-quotes
48c44d61 update error message in prior test
4dabf691 Convert strings ourselves instead of using `eval`
2d6d5f9c Merge pull request #2471 from Kodiologist/pattern-errs
```

</details>

ahw, ohkayh.

just today i was thinking again about posting this idea to git-scm that i had for quite some time now
which will solve this problem of lost branching info with merge-rebased...

ur input serves as a solid example for validity of that idea.

**Pull request merged**
