### PR TITLE
Burninate botsbuildbots

### LINKED ISSUE #1961: Remove Botsbuildbots contrib module
`Bobsbuildbots` currently isn't tested or documented in the docs and I'm not sure what it even does. As of right now it doesn't actually work because it uses the old bracketed `import` syntax:
`(import [requests])`
It also doesn't really align with what the contrib module has become of late, namely a testing ground for language features and functionality. Maybe I'm just not understanding what the point of it is, but I'd vote to remove it barring some more persuasive explanation for why we should keep it.

### PR DESCRIPTION
**Pull request by Kodiologist**
Closes #1961.

Third time's the charm (#1189, #1601).

### CODE REVIEW

**Comment by allison-casey** [comment]
`botsbuildbots` was mentioned in `NEWS` before so you might as well mention it in `Removals`

**Comment by Kodiologist** [comment]
It's always been undocumented and it was already broken for several releases, though.

**Comment by allison-casey** [comment]
Also true :woman_shrugging:

**Review by allison-casey — APPROVED** [review]
Burninating the broken modules :fire:

**Review by scauligi — APPROVED** [review]

**Pull request merged**
