### PR TITLE
Assert now may take an optional label, like in Python

### PR DESCRIPTION
**Pull request by rhaps0dy**

### CODE REVIEW

**Comment by Foxboron** [comment]
Now #767 can be happy!
\o/ LGTM!
:shipit:

**Comment by paultag** [comment]
LGTM! Thanks! :dancer:

**Comment by paultag** [comment]
Hey, @rhaps0dy mind sending a PR adding yourself to AUTHORS?

**Comment by rhaps0dy** [comment]
Sure, give me a sec :)

**Pull request merged**
