### PR TITLE
Give an error on empty attributes

### LINKED ISSUE #1137: "foo".format is legal syntax but does the wrong thing
`(. "foo" format)` works, but `"foo".format` doesn't (`NameError: name '' is not defined`). hy2py shows that `"foo".format` is parsed as two separate statements, `"foo"` and `.format`.

### PR DESCRIPTION
**Pull request by kirbyfan64**
Closes #1137.

### CODE REVIEW

**Comment by Kodiologist** [comment]
You're fast!

For completeness, I would add tests for `2.foo`, `"hello".foo`, and `[2].foo`.

**Comment by Kodiologist** [comment]
It looks like the test fails because `2.foo` compiles, which happens because Hy interprets the `2` here as a reference to a variable named `2`. Is that a parser bug?

**Comment by kirbyfan64** [comment]
Aaaaaand that's what happens when I write the tests and don't run them...

@Kodiologist I think that probably would be classified as a bug, since I can't think of a single reason why someone would do something that stupid, and I think this is the only way you can use a number as a variable.

**Comment by kirbyfan64** [comment]
Meanwhile, I just removed the test.

**Comment by kirbyfan64** [comment]
Anyone else want to approve this? :heart:

**Pull request merged**
