### PR TITLE
`hy2py` recursive

### PR DESCRIPTION
**Pull request by dm9pZCAq**
add sub commands:
* `file` - to compile single file
* `module` - to compile module directory

---
compiling module
```sh
hy2py module my_module compiled/my_module
```

---
add `--as-module` flag to `file` sub command to compile file as part of module (related to  #2204)

for example:
```sh
mkdir my_module
touch 'my_module/__init__.py'
echo '(setv foo 1)' > my_module/macros.hy
echo '(require .macros *)' > my_module/args.hy
hy2py file --as-module my_module.args my_module/args.hy
```

---
fixes: #2079

### CODE REVIEW

**Comment by Kodiologist** [comment]
Looks like tests are failing on GitHub. Do you have them passing locally?

**Comment by dm9pZCAq** [comment]
no, i forget it

i will fix it soon

**Comment by dm9pZCAq** [comment]
so... any thoughts on this?

**Comment by Kodiologist** [comment]
Don't worry; I don't forget about PRs. It's just that I've been busy and this will take some thought.

**Comment by Kodiologist** [comment]
You seem relatively sensitive about using your real name. You know that for copyright-management reasons, in order to merge this, we'll want you to add a line (with your real name) to AUTHORS, right? See CONTRIBUTING.rst.

I'm not totally clear about the ramifications of your approach of applying `hy2py` to modules rather than directories. Is this necessary solely for #2204, or for other reasons, too? I'm not sure how well it addresses #2204, since you can also get that error with `hy`, not just `hy2py`, and I think you haven't changed anything with respect to `hy`.

**Comment by dm9pZCAq** [comment]
> You seem relatively sensitive about using your real name.

yes :)

> You know that for copyright-management reasons, in order to merge this, we'll want you to add a line (with your real name) to AUTHORS, right? See CONTRIBUTING.rst.

what is this "copyright-management reasons"?

also how could you verify if "some" name is "real name"?

---

> I'm not totally clear about the ramifications of your approach of applying hy2py to modules rather than directories.
> I'm not sure how well it addresses #2204, since you can also get that error with hy, not just hy2py, and I think you haven't changed anything with respect to hy.

hmm, i think  i can try to fix this in `require` instead of just in `hy2py`

**Comment by Kodiologist** [comment]
> what is this "copyright-management reasons"?

As with a lot of free software, the copyright to Hy is collectively owned by all its authors. That means that if we had to do certain legal shenanigans like change the license or enforce our license in court, we'd have to get at least nominal participation in the process from each author, or back out their contributions. So if the connection between code we have and the person who wrote it is tenuous, that code is a liability.

> also how could you verify if "some" name is "real name"?

So far, we haven't, on the grounds of hoping that nobody is petty enough to lie about their name in AUTHORS. We don't have the legal resources of organizations like the FSF, anyway.

**Comment by dm9pZCAq** [comment]
`hy` is licensed under `MIT` and as i understand anyone can do [basically anything](https://choosealicense.com/licenses/mit/) with this software 
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND...

so i don't understand how you can "enforce our license in court"

---
> So if the connection between code we have and the person who wrote it is tenuous, that code is a liability.

why? i just want to do `hy` better for me and everyone else and i don't care about anything related to license (again: it is `MIT`)

**Comment by Kodiologist** [comment]
Getting into a detailed debate about the legal issues here probably wouldn't be fruitful, because I'm not a lawyer. Suffice it to say that I personally am not comfortable merging nontrivial anonymous contributions. @hylang/core, what say you?

**Comment by Kodiologist** [comment]
@dm9pZCAq Looks like this isn't gonna happen. Are you sure you don't want to tell us your name? Have some pride and take credit. This isn't politically sensitive work. If you're worried that your commit timestamps would show that you're working on Hy when you're supposed to be doing something else, remember that Git allows you to fake those.

**Comment by dm9pZCAq** [comment]
ok :unamused:, i will add name and fix `require` but a little later

now i don't have much time

**Comment by gilch** [comment]
I wonder if a public domain dedication would suffice. Can that even be done pseudonymously? IANAL either.

**Comment by allison-casey** [comment]
i will see if there's precedent for using anonymous names in a project like this. i have to believe this has already been litigated before in another open source project

**Comment by allison-casey** [comment]
So looking through scikit-learn, scipy, pandas, numpy, and matplotlib; it seems that the AUTHORS file is almost wholly unnecessary. None of those projects maintain a list of authors and emails and just rely on github's [contributors](https://github.com/hylang/hy/graphs/contributors) page to to track who's touched the project (it's worth noting that all of those projects are under the stricter BSD license too). Unless someone has a substantive reason to continue using it, then I'd honestly suggest we just delete it.

**Comment by Kodiologist** [comment]
Not all GitHub users have their name in their profile, though. And I imagine that if somebody deletes their account, their user information isn't preserved in the contributors page.

**Comment by allison-casey** [comment]
Oh, i mean is there a verifiable legal reason we can point to for keeping an authors log when a bunch of other established projects don't; or is this something we're doing because we've always been doing it? Because as far as I can tell there doesn't seem to be any problem with anonymous users contributing code

**Comment by Kodiologist** [comment]
> i mean is there a verifiable legal reason

Nope, just our best guesses. I'm afraid we aren't getting actual legal counsel anytime soon.

**Comment by allison-casey** [comment]
let me ask around and see if i can get an answer out of anybody

**Comment by Kodiologist** [comment]
If you have access to an expert, that would be great, even if they can't speak on the record. The way I would phrase the question is "Is there any feasible situation in which an Expat-licensed project would need the names and contact information of all of its authors?"

**Comment by Kodiologist** [comment]
For what it's worth, my experience with projects that are careful about legal issues is that GNU has you sign a form to relinquish your copyright, whereas CPython has you sign [a form](https://www.python.org/psf/contrib/contrib-form/) to license your contributions and allow the PSF to relicense them. In both cases, since you're signing a legal document, you're asked for your name.

**Comment by allison-casey** [comment]
The answer is "probably not", but friend is double checking.

**Comment by Kodiologist** [comment]
@dm9pZCAq I'm closing this due to lack of activity (regarding the code, not the AUTHORS kerfuffle). If you finish this up, let's reopen it once it's ready for review.

**Pull request closed without merging**
