### PR TITLE
Fix completion not unmangling names

### PR DESCRIPTION
**Pull request by scauligi**
This was really getting under my skin.

### CODE REVIEW

**Comment by Kodiologist** [comment]
Because `unmangle` can't handle everything, this seem to prevent the completer from being able to complete some symbols, such as the malformed mangled symbol `hyx_XaX`.

**Comment by scauligi** [comment]
Good catch, should be handled now. Are there any other edge cases that we might run into?

**Comment by Kodiologist** [comment]
Not that I can think of.

Catching `Exception` seems dangerous; can you narrow which types you catch?

`namespaces` and `test_cases` are only used once each, so they can be inlined.

I think that's about it.

**Comment by Kodiologist** [comment]
@scauligi Are you still working on this, or shall I look at it again?

**Comment by scauligi** [comment]
oh shoot, forgot to post here
yeah it should be good for review

**Comment by Kodiologist** [comment]
Looks good to me. Rebase it and merge.

**Review by Kodiologist — APPROVED** [review]

**Pull request merged**
