### PR TITLE
Remove Toolz reimplementations

### PR DESCRIPTION
**Pull request by Kodiologist**

### CODE REVIEW

**Comment by allison-casey** [comment]
if `by2s` is going to be imported into other modules, it should have a docstring imo. Otherwise looks good to me

**Comment by Kodiologist** [comment]
Okay, I figured it didn't need one because it's only for internal use, but it's no trouble. Done.

**Comment by allison-casey** [comment]
doing the full autodoc `args` `returns` etc would be overkill, but it's good practice to have something for those methods. 
how is the unclosed bracket string `  #[[Returns the given iterable in pairs.` not a syntax error btw? It works, but it seems like it shouldn't

**Review by allison-casey — DISMISSED** [review]

**Comment by Kodiologist** [comment]
Oops, you're right. I forgot to check the whole docs directory. This PR was a surprising amount of work.

**Comment by allison-casey** [comment]
I can go through and fix the docs for you. `by2s` won't work since it doesn't support `fillvalue` and will drop the last entry if there's an odd number, but we can just use the `itertools.grouper` recipe for that

**Comment by Kodiologist** [comment]
That would be convenient. Thanks.

**Comment by allison-casey** [comment]
Docs are fixed for this and the itertools alias removals

**Review by allison-casey — APPROVED** [review]

**Pull request merged**
