### PR TITLE
Fix issue found by @tuturto in #903 (again!)

### PR DESCRIPTION
**Pull request by kirbyfan64**
Supersedes #958, whose commit history I somehow butchered. @gilch Can you try it?

### CODE REVIEW

**Comment by gilch** [comment]
Merge conflicts now. @kirbyfan64 have you figured out what's causing the `getargspec` problem?

**Comment by paultag** [comment]
Test cases? Also, what exactly is this doing? And mind merging with master?

**Comment by gilch** [comment]
It's a lot of complexity for marginal benefit over pre- #924. There's six `if`s and a `try/except`. All code paths need unit tests. Testing is maybe not as hard as it sounds, since it takes different Python implementations to reach these anyway, so a lot of the paths could be reached from one test.

I'm still concerned about that `try/except`, since a the generic lambda it returns defeats the whole purpose of #924. Can you be more specific with the caught exception? Can you avoid generating an exception in the first place?

You can test #903 from that branch just by pasting the macro code in the repl.

**Comment by gilch** [comment]
The code to paste in:
```Hy
(defmacro defmacro! [name args &rest body]
  "like defmacro/g! plus args that start with o! will automatically evaluate
   once only and be bound to the equivalent g!"
  (setv os (list-comp s [s args] (.startswith s "o!"))
        gs (list-comp (HySymbol (+ "g!" (cut s 2))) [s os]))
  `(defmacro/g! ~name ~args
     `(do (setv ~@(interleave ~gs ~os))
          ~@~body)))

(defn expensive-get-number [] (print "spam") 14)
(defmacro! triple-3 [o!n] `(+ ~g!n ~g!n ~g!n))
(triple-3 (expensive-get-number))
```

**Comment by kirbyfan64** [comment]
Here's a smaller test case:

```
(defmacro f [@] `nil)
(f)
```

**Comment by kirbyfan64** [comment]
All cleaned up and merged!

**Comment by Kodiologist** [comment]
I've confirmed that the bug still exists, and there are no merge conflicts, but trying to launch Hy (with Python 3.5.2) raises `AttributeError: 'FullArgSpec' object has no attribute 'keywords'` in `macros.py`. Want to update it, Ryan?

**Comment by kirbyfan64** [comment]
Ugh...this isn't going to work. Remember the `unsupported callable` error? It's because, on Python 3, *`getargspec` raises an error on invalid parameter names*.

So now we'd also have to remove support for non-identifier arguments...

**Comment by Kodiologist** [comment]
Do you think that's a limitation that we should report upstream to the Python folks?

**Comment by kirbyfan64** [comment]
@Kodiologist It's an explicit check though. I think it's just an intentional limitation...

**Comment by Kodiologist** [comment]
> Might still run it by python-ideas though.

I think you should. If the idea is shot down, then apparently, we'll have to restrict ourselves to parameters that are legal Python identifiers. If it isn't, then we can open an issue to remind ourselves to fix this bug once Python allows us to.

**Comment by kirbyfan64** [comment]
@Kodiologist  FWIW, wouldn't this fail then on Python versions <3.7?

**Comment by Kodiologist** [comment]
Yeah, we'd have to gate the tests for this by Python version.

**Comment by gilch** [comment]
> So now we'd also have to remove support for non-identifier arguments...

This is just for improved error messages, right? #924 introduced this problem. I don't think its worth restricting Hy like that just for better diagnostic information. We can come up with some other way to debug macros.

**Comment by gilch** [comment]
Closed by #1172

**Pull request closed without merging**
