### PR TITLE
Just remove `def`

### PR DESCRIPTION
**Pull request by vodik**
Simply removed `def` keyword and replaces it with `setv` everywhere. See #1475 and #911.

### CODE REVIEW

**Comment by Kodiologist** [comment]
I think we should decide what we're going to do with it before removing it; for example, replacing `defn` with it (as I'd like to do).

**Comment by vodik** [comment]
Yup, that's fair, but that should be easy to add on top of this.

**Comment by Kodiologist** [comment]
That's true, and this alone is more likely to get consensus. So let's go with it. Just update the `def / setv` section of `api.rst` and update NEWS and I think it's good to go.

**Comment by vodik** [comment]
Done. I'm pretty sure `def` has been removed *everywhere* now.

**Pull request merged**
