### PR TITLE
Drop support for Python 2

### LINKED ISSUE #1217: Drop support for Python 2
This is something that's been brought up many times but has no dedicated issue. Even if we don't want to do this soon, we might want to put it on a milestone or something.

Dropping Python 2 would let us clean up the codebase a lot and make it easier to support Python 3's new features.

If there's anybody who uses Hy on Python 2 and really can't upgrade, at least until another library adds Python 3 support, you should say that here and mention what you're waiting for. We have no idea how many of you exist.

### PR DESCRIPTION
**Pull request by Kodiologist**
Closes #1217.

The code has a net shrinkage of over 700 lines.

### CODE REVIEW

**Comment by Kodiologist** [comment]
There's still a test failure on Python 3.8 that I'm pretty sure has nothing to do with this PR. I can't replicate it on my own machine, so I think it's due to a change to Python since the release of 3.8.0a4. 3.8.0b1 should be out pretty soon, so let's just wait and see.

**Comment by Kodiologist** [comment]
@brandonwillard, you may be interested in looking at [the test failure](https://travis-ci.org/hylang/hy/builds/541415078) because it's from one of your tests of macro scoping, `test-macro-namespace-resolution`.

**Comment by brandonwillard** [comment]
OK, will do.

**Comment by Kodiologist** [comment]
I think I got it. See #1784.

**Pull request merged**
