### PR TITLE
Replace individual CI checks with pre-commit

### PR DESCRIPTION
**Pull request by lafrenierejm**
This is a follow-up to #2209. It seems to me that using pre-commit for the CI checks is cleaner than effectively re-writing the pre-commit config for GitHub Actions.

### CODE REVIEW

**Comment by lafrenierejm** [comment]
https://github.com/lafrenierejm/hy/runs/5087548631?check_suite_focus=true is an example of this running against my personal fork.

**Comment by Kodiologist** [comment]
Seems like a straightforward improvement. Don't repeat yourself and all that.

**Review by Kodiologist — APPROVED** [review]

**Comment by Kodiologist** [comment]
This is weird. I rebased onto master and the checks started running on GitHub. They hadn't previously. Then I rebased back to how the branch was before my previous rebase and they're running again, although this should be the same commit that I started with.

**Comment by allie-jo** [comment]
This is a bugfix for PR #2209 which misunderstood how github workflows `on: {paths: ...}` worked. Code checks should have been running on all PR's including #2223.

**Comment by lafrenierejm** [comment]
> This is a bugfix for PR #2209 which misunderstood how github workflows `on: {paths: ...}` worked. Code checks should have been running on all PR's including #2223. 

Indeed. I didn't intend or indicate this as a bug fix just because I didn't realize there were issues with the current CI; the behavior of this PR is what I originally intended with #2209.

**Comment by allison-casey** [comment]
@lafrenierejm in the vein of getting this working. Can you please rebase off master, create a cleanup commit to fix the syntax currently failing CI, and then add it's hash to `.git-blame-ignore-revs`

**Comment by lafrenierejm** [comment]
> Can you please rebase off master, create a cleanup commit to fix the syntax currently failing CI, and then add it's hash to `.git-blame-ignore-revs`

@allison-casey Done.

**Comment by lafrenierejm** [comment]
@brandonwillard I believe you had endorsed #2203. Would you be willing to review this?

**Review by brandonwillard — APPROVED** [review]

**Pull request merged**
