### PR TITLE
slice overshadow corrections as hysymbol change

### PR DESCRIPTION
**Pull request by calben**
This is a new correction to slicing that renames the slice operation to cut, modifying all appropriate tests.
The HySymbol("slice") is now HySymbol("cut").

No other functionality was changed.

A much simpler solution than the stuff that I did before :smile: 

The previous pull request associated with this is #508 which was a response to #505 and previously mentioned in #381.
The majority of discussion on the topic was in #508.

### CODE REVIEW

**Comment by paultag** [comment]
@hylang/core Can we get this in? We'll have to do a `0.12`, but I'm OK with that. Thoughts>

**Comment by algernon** [comment]
Since we're breaking the world anyway, lets get this in. Needs a rebase, though (I can do that locally, if need be).

:+1:

**Comment by gilch** [comment]
Can we rename `cut` to `:` instead? Or perhaps add an alias reader macro `#:` that translates to `cut`?

Also, if we could use the `:` as keyword separators, it could look more like Python's slices and we wouldn't have to insert `nil`s so much.

**Comment by calben** [comment]
a reader macro could work well, but binding `cut` to `:` instead may have nasty consequences when using packages like numpy.

**Comment by algernon** [comment]
I'll merge this as-is (after patching up the conflicts) ~tomorrow. The name is fine, and a reader macro can be introduced later (or locally, if someone really prefers).

**Comment by algernon** [comment]
After rebasing, there are some test failures, as new tests that use `slice` were introduced after the PR was made. I'll correct those, and merge the rebased stuff in a bit.

**Pull request closed without merging**
