### PR TITLE
raw-input is undefined, replace with input. discussed here: https://g…

### PR DESCRIPTION
**Pull request by caustin-usgs**
…ithub.com/hylang/hy/issues/259

### CODE REVIEW

**Comment by Kodiologist** [comment]
`raw_input` is a Python 2 builtin and hence available in Hy running under Python 2. Changing the tutorial to use Python 3 would make sense, so I'd encourage you to do that if you're interested, but we probably shouldn't switch versions mid-tutorial without warning.

(Actually, in Hy under Python 2, `input` is aliased to `raw_input`, but this is pretty confusing and hence probably not a good idea to spring on the reader of the tutorial at this point.)

**Comment by caustin-usgs** [comment]
@Kodiologist thanks for the clarification, makes sense

**Comment by caustin-usgs** [comment]
will open a new PR for the switch to python 3 syntax

**Comment by freezas** [comment]
@caustin-usgs Have you already made a branch to Python 3 syntax? I'm willing to help a hand or start a new branch if you haven't got the chance to work on this.

**Comment by freezas** [comment]
No problem ;-)

**Pull request closed without merging**
