### PR TITLE
Let setv take pairs of arguments

### PR DESCRIPTION
**Pull request by kirbyfan64**
@algernon Beat you to it. ;)

Ref. #844.

### CODE REVIEW

**Comment by paultag** [comment]
I guess omitting braces is fine here, since there's no body following

My only hangup is if there's a consistency issue with the rest of the language - @hylang/core anyone see a need for braces or am I losing it?

If no one else sees a problem, I've got a :+1: LGTM here!

**Comment by paultag** [comment]
P.S., forgot to say - I love the return semantics.

**Comment by gilch** [comment]
This is supposed to be sequential, right? Can you add a test something like 
```
(setv y False
      x True
      y x)
(assert y)
```

**Comment by gilch** [comment]
@paultag I don't think we need braces here.

**Comment by agentultra** [comment]
seconded.

**Comment by algernon** [comment]
Looks good. A test @gilch described would be great, though, I'd merge this much more confidently. Big :+1: otherwise!

**Comment by kirbyfan64** [comment]
@gilch @algernon Test added (to same commit: no squashing needed).

**Comment by zackmdavis** [comment]
squirrel

**Pull request merged**
