### PR TITLE
Add Homebrew install to docs

### PR DESCRIPTION
**Pull request by SeekingMeaning**
https://formulae.brew.sh/formula/hy

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
Sure, where would be a good place for that?

**Comment by Kodiologist** [comment]
I'm against this. I don't think it's our job to keep track of repository-specific installation instructions. Besides, we want to encourage users to use PyPI or install directly from the source.

**Comment by brandonwillard** [comment]
> I'm against this. I don't think it's our job to keep track of repository-specific installation instructions. Besides, we want to encourage users to use PyPI or install directly from the source.

Agreed.

**Comment by SeekingMeaning** [comment]
Sure, no problem, we'll try to keep the package updated on our side.

**Pull request closed without merging**
