### PR TITLE
Backport fix Python 3.5.1 support by converting kwargs and stararg to str as late as possible

### PR DESCRIPTION
**Pull request by tianon**
(cherry picked from commit 9d8e4ddb8098dab39eb3d4f7ef89dc7ccd13a49f; PR #997)

### CODE REVIEW

**Comment by tianon** [comment]
Will rebase for CI once #1007 settles.

**Comment by tianon** [comment]
It might also make sense to include #983 here so we're testing Python 3.5 via CI for the new branch -- thoughts? (Happy to add those two commits if there's some agreement.)

**Comment by paultag** [comment]
@tianon sounds legit to me, yep. That's the only way we can test the intended patch for this release, the 3.5 support

**Comment by tianon** [comment]
How about #843?  If I add that one also, the 3.5 one applies completely clean without any conflicts (although I'm happy to resolve the conflicts instead if you'd rather).

**Comment by paultag** [comment]
I'm reluctant to drop 2.6 in a micro stable release update

**Comment by paultag** [comment]
I think we should just resolve conflicts for now

**Comment by tianon** [comment]
Ok cool, will do.

**Comment by tianon** [comment]
Whew, I had to also include #800 for complete Python 3.5 support, but that does it. :+1:  (Only `pypy` still running in CI now.)

**Comment by tianon** [comment]
Woot, green! :metal:

**Comment by paultag** [comment]
LGTM! RFR @hylang/core

**Pull request merged**
