### PR TITLE
Hy 0.20.0

### PR DESCRIPTION
**Pull request by Kodiologist**
@hylang/core, remember that we need two approvals to release.

### CODE REVIEW

**Review by brandonwillard — APPROVED** [review]

**Review by refi64 — APPROVED** [review]

**Comment by Kodiologist** [comment]
@allison-casey Any hints on updating https://hylang.github.io/hy-interpreter?

**Comment by allison-casey** [comment]
Should just be a zappa deploy with the new deps. I'll push an update this week.

**Comment by allison-casey** [comment]
Interpreter has been updated to `0.20.0`

**Comment by Kodiologist** [comment]
Great, thank you.

**Pull request merged**
