### PR TITLE
Expose `read`, `read_str`, and `eval` in Python

### LINKED ISSUE #1256: Official support for evaluating strings of Hy code from Python
Is it possible to embed some hy code inside a python file? As opposed to having the whole file be full on hy?

### PR DESCRIPTION
**Pull request by jdanford**
Fixes #1256 (and replaces #1365)

### CODE REVIEW

**Comment by Kodiologist** [comment]
Generally, this looks good.

- See `CONTRIBUTING.rst` for guidelines about commit messages, `NEWS`, and `AUTHORS`.
- In `test_importer`, import `read_str` and `hy_eval` directly from `hy`, since that's the interface you want to test.
- Define `eval_str` inside `test_eval`, since it's only used there.

**Comment by Kodiologist** [comment]
Also, could you describe the `eof` parameter of `read` in its docstring? Alternatively, `read` could perhaps be rewritten without it. The current implementation looks kind of weird.

**Comment by jdanford** [comment]
All fixes have been made!

**Comment by Kodiologist** [comment]
Cool. Don't forget about https://github.com/hylang/hy/pull/1369#issuecomment-320468126.

**Comment by jdanford** [comment]
Forgot to do a `git add`, fixed now!

**Comment by Kodiologist** [comment]
I thought that might be it. It happens to the best of us.

**Pull request merged**
