### PR TITLE
Fix a bug where the compiler doesn't properly handle unquote-splice

### PR DESCRIPTION
**Pull request by vodik**
Added test coverage as well

### CODE REVIEW

**Comment by vodik** [comment]
@Kodiologist probably because its ambiguous: `(quote @)` a.k.a. matmul

**Comment by Kodiologist** [comment]
Ah, all right, then.

**Comment by vodik** [comment]
@Kodiologist hmmm, wonder if it makes sense to list the expression we failed to unquote though.

**Comment by Kodiologist** [comment]
Don't our fancy error messages already do that, by pointing to the part of the code where you tried to unquote something?

**Comment by vodik** [comment]
Yeah, its a good point. Its just harder to interpret with `~@`. But yeah, I rest my case.

**Comment by gilch** [comment]
```
=> `(~@"mu")
HyExpression([
  'm',
  'u'])
=> `(~@ "mu")
HyExpression([
  <function hyx_Xcommercial_atX at 0x000001FDC787A730>,
  HyString('mu')])
=> `(~ @ "mu")
HyExpression([
  HySymbol('~'),
  HySymbol('@'),
  HyString('mu')])
```
Interesting that three interpretations are possible since `~` and `@` are also both operators (invert and matmul). Be careful with spacing when using these. Probably should be documented better.

**Pull request merged**
