### PR TITLE
Fix cmdline error to string conversion.

### PR DESCRIPTION
**Pull request by Scorpil**
Fixes issue #982.

### CODE REVIEW

**Comment by paultag** [comment]
Hilarious, yeah. Totally.

What an awesome bug.

Right, so this looks good and it totally fixes the issue, so I say we're good. @hylang/core RFR

I mildly prefer `.format` to `%`, but it's OK. Other things in the compiler use modulo, so I'm tempted to punt on that.

Nice work thanks!

**Comment by paultag** [comment]
@Scorpil Also, looks like you're a new contributor - mind opening a new PR adding yourself to AUTHORS?

**Comment by berkerpeksag** [comment]
I'd prefer `print(str(e), file=sys.stderr)` over `sys.stderr.write("%s\n", str(e))`.

**Comment by berkerpeksag** [comment]
Also, I don't fully understand how this solves #982. I think the main problem is in clint and we need to encode `self.message` before passing it to `colored.yellow()`: https://github.com/hylang/hy/blob/master/hy/errors.py#L104 I don't have a development environment right now so I might be horribly wrong :)

Thanks!

**Comment by paultag** [comment]
@berkerpeksag I think you're right, I was also surprised this fixed the bug when I was just looking at the diff -- I your point really resonates with me right now, (as a strong believer of the unicode sandwich)

@berkerpeksag I'll leave this PR up to you!

**Comment by Scorpil** [comment]
@berkerpeksag i've checked it - you're right. self.message there is correct unicode value on our side, so clint supposed to handle it correctly, but because of the bug it doesn't. I've sent PR https://github.com/kennethreitz/clint/pull/153 but it can take a while.

In the meantime, I've updated my fix to work around this bug by sending encoded string instead of unicode.

**Comment by Foxboron** [comment]
This looks great!
LGTM!

**Comment by berkerpeksag** [comment]
Looks great to me, too. Could you please squash your commits?

Thanks!

**Comment by Scorpil** [comment]
Done. Glad to help.

**Pull request merged**
