### PR TITLE
Avoid evaluating quoted f-strings

### PR DESCRIPTION
**Pull request by refi64**
Trivial, yay or nay?

### CODE REVIEW

**Comment by Kodiologist** [comment]
Great work. Unfortunately, this change would probably not be seen as trivial.

I think the test isn't quite what we want. You're checking the stringification of the model. It would be better to test that the replacement field is evaluated at the right time, with something like:

```
(setv quoted 'f"hello {world}")
(with [(pytest.raises UnboundLocalError)]
  (eval quoted))
(setv world "goodbye")
(assert (= (eval quoted) "hello goodbye"))
```

**Comment by Kodiologist** [comment]
@refi64 Do you plan on finishing this? If not, I think I'll pick it up.

**Comment by refi64** [comment]
Oof forgot, I'll finish it tomorrow

**Comment by refi64** [comment]
Okay finally updated!

**Comment by Kodiologist** [comment]
Noice. I'll add a NEWS item and merge.

**Pull request merged**
