### PR TITLE
Fix: subscript type annotations

### PR DESCRIPTION
**Pull request by allison-casey**
hy reader wasn't properly parsing expressions after `^`

### CODE REVIEW

**Comment by Kodiologist** [comment]
The test results suggest a conflict with the exclusive-or operator.

**Comment by allison-casey** [comment]
yeah just noticed that slipped past since i forgot to remove `__pycache__` when running tests

**Comment by Kodiologist** [comment]
My usual local testing command is

    git clean -fx '*/__pycache__/*' && pytest --ignore=tests/test_bin.py

**Comment by allison-casey** [comment]
there we go. all better

**Review by Kodiologist — APPROVED** [review]
This seems to have been a regression since 1.0a4, so no NEWS line is required.

**Comment by allison-casey** [comment]
yeah, we just didn't have a test for subscript types. Can we actually get this merged before the 3 day wait since it's a small fix and a pretty impactful regression

**Comment by Kodiologist** [comment]
Yeah, that's legit.

**Pull request merged**
