### PR TITLE
Expose `read`, `read_str`, and `eval` as top-level functions in Python

### LINKED ISSUE #1256: Official support for evaluating strings of Hy code from Python
Is it possible to embed some hy code inside a python file? As opposed to having the whole file be full on hy?

### PR DESCRIPTION
**Pull request by jdanford**
Fixes #1256

### CODE REVIEW

**Comment by Kodiologist** [comment]
All right, how about some tests and documentation?

**Comment by jdanford** [comment]
All three functions have docstrings, but tests would be good, so I'll add some as soon as I get a chance.

**Comment by Kodiologist** [comment]
By "documentation", I mean the manual, not docstrings. Think of people like the guy who wrote #1256. How would they know without asking that using these functions is how you can use Hy in Python?

**Comment by jdanford** [comment]
Of course, not sure why I misunderstood! Should I add a new section under [Using Hy from Python](http://docs.hylang.org/en/master/language/interop.html#using-hy-from-python)?

**Comment by Kodiologist** [comment]
Sure, that makes sense.

**Comment by jdanford** [comment]
Whoops, just noticed I did this on `master` instead of a branch! New PR is #1369

**Pull request closed without merging**
