### PR TITLE
add `symbol?` function to `hy.core`

### PR DESCRIPTION
**Pull request by larme**
`symbol?` will test if the input is an instance of HySymbol. It's useful when writing macros.

### CODE REVIEW

**Comment by agentultra** [comment]
:+1:

**Comment by Foxboron** [comment]
Needs documentation! Also a possible entry in AUTHORS?

Otherwise: +1

**Comment by theanalyst** [comment]
Could you please add the docs as well, we generally forget to add the documentation once the code is merged in

+1

**Comment by larme** [comment]
Documents added.

**Comment by Foxboron** [comment]
Looks good to me!

:shipit:

**Pull request merged**
