### PR TITLE
Remove 2.6 entirely from test runners

### PR DESCRIPTION
**Pull request by paultag**
(But not codepaths, in case someone cares)

### CODE REVIEW

**Comment by kirbyfan64** [comment]
So does this mean Hy no longer supports 2.6?

**Comment by Foxboron** [comment]
No, i like Python2.6
















Not at all. LGTM! :shipit:

**Comment by paultag** [comment]
@kirbyfan64 it means I don't really want 2.6 to block test passage anymore -- I didn't pull our codepaths, so it'll continue until it becomes too much of a maintenance burden -- thoughts?

**Comment by paultag** [comment]
(Python 2.6 was officially EOL'd in 2013)

**Comment by paultag** [comment]
Let's wait to make sure @kirbyfan64 doesn't have blocking objections, and if we're good, we'll merge!

**Comment by kirbyfan64** [comment]
@paultag Hahaha, I hate 2.6 just as much as everyone else. :O

I was just curious because I had to add an explicit call to make set literals work on 2.6 so the tests could pass.

**Comment by paultag** [comment]
@kirbyfan64 fuck it, let's drop 2.6 - if someone needs it, we can re-introduce. Fire away with set literals, that counts as a maintenance burden

**Pull request merged**
