### PR TITLE
Hy 0.15.0

### PR DESCRIPTION
**Pull request by Kodiologist**
Recall that the two-week merge rule doesn't apply to this PR, since it's the PR for a new release.

Are there any other PRs folks want to get in before we release?

### CODE REVIEW

**Comment by Kodiologist** [comment]
@hylang/core, let's try to get this out soon, since it provides Python 3.7 compatibility, and Python 3.7 is out.

**Comment by Kodiologist** [comment]
@hylang/core, is there a problem? We all want a new release, right?

**Comment by tuturto** [comment]
True, rather have new release out sooner than later. Personally I don't know any other PRs I would like to see in the next release that wouldn't already be included.

:+1: for the release from me.

**Comment by Kodiologist** [comment]
Thanks. I'll rebase and do the release tomorrow.

**Pull request merged**
