### PR TITLE
Modify multimethods to use dispatching function

### PR DESCRIPTION
**Pull request by tuturto**
Based very heavily on: https://adambard.com/blog/implementing-multimethods-in-python/

### CODE REVIEW

**Comment by Foxboron** [comment]
Hurm. Should try and figure out a new name for the `defmulti` removed in this patch. People are using it afaik, so we can't just remove it.

Other then that. Looks pretty great!
:+1:

**Comment by tuturto** [comment]
Functionality similar to old behaviour can be done by using ```len``` as dispatch function and using ```&rest args``` in function signature. But it does require pretty substantial modifications to existing code. Hm.. maybe we can come up with a different name for new ```defmulti``` macro and leave the arity overloading in place? Or just decide to use the same name, but in different module, thus allowing users to ```require``` either one, but not both at the same time.

**Comment by Foxboron** [comment]
The old `defmulti` should be renamed IMO. The name was bad and doesnt really reflect how `defmulti` works inn clojure as an example/

**Comment by tuturto** [comment]
How about a name that reflects that it's doing arity overloading? ``arity-overload`` or just simple ``defoverload``? I'm finding it hard to find a good name.

**Comment by Foxboron** [comment]
`defoverload` could work. yeah!

**Comment by gilch** [comment]
I like the sound of it but it's too long.

**Comment by gilch** [comment]
Maybe we should just call it `defn` like Clojure does. We still have `lambda`. You can set up the macro to work just like `defn` does now when there's only one arity. Even if we don't move it into core yet, we could shadow the normal `defn`, couldn't we?

**Comment by Foxboron** [comment]
Ah yes! Thats a better idea honestly. Should i make a another PR or should we include the rename in this?

**Comment by gilch** [comment]
We could make it work either way, but I'd suggest another PR, since these are technically separate issues that just happen to have a name conflict.

**Comment by tuturto** [comment]
naming the arity uploading macro to ```defn``` and making a special case to work like regular ```defn```is good and elegant solution. I like that.

**Comment by algernon** [comment]
Looks good to me, and I agree with the previous suggestions re: old `defmulti`.

:shipit:

**Comment by Kodiologist** [comment]
Hey Tuukka, it looks like everybody's happy with the new code, but I don't think we can in good conscience kill the old `defmulti` unless we know nobody's using it. I recommend simply reverting the relevant deletions, and having both `defmulti`s coexist for now.

**Comment by gilch** [comment]
@Kodiologist I disagree, we broke API pretty seriously already for the Grand Language Cleanup (still pending). The time for more breaking changes is now, not later.

**Comment by Kodiologist** [comment]
@gilch Eh, good point. Shall I merge?

**Comment by gilch** [comment]
> Ah yes! Thats a better idea honestly. Should i make a another PR or should we include the rename in this?

@Foxboron I never saw that other PR? You can do the rename in this if it's easier, otherwise can we merge this?

**Comment by tuturto** [comment]
@Kodiologist I wouldn't want to have two constructs that have same name, but different behaviour in the language (even if they're in contrib module). @gilch suggested that we rename old ``defmulti`` to ``defn`` and have it detect when we're arity overloading and when it's just a normal function definition. I like the idea, but haven't done anything for it. I try to have a look at that some time soon, hopefully.

**Comment by tuturto** [comment]
I added previous version of ``defmulti`` and renamed it to ``defn``. This version of ``defn`` detects when it should make an arity-overloaded version instead of regular one. All tests pass, but there might be some corner cases somewhere that don't really work (but that's why it's in contrib anyway).

**Pull request merged**
