### PR TITLE
Add handling for "=" syntax in f-strings

### LINKED ISSUE #1948: Add support for "=" syntax in  f-strings
Since 3.8, Python has had "[equal sign syntax](https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals)" in f-strings, which can be useful for debugging. For example:

```
In [2]: the_string = "foo"

In [9]: f"{the_string=}"
Out[12]: "the_string='foo'"

In [13]: f"{the_string=:5}"
Out[16]: 'the_string=foo  '

In [19]: from datetime import datetime; the_object=datetime.now()

In [29]: f"{the_object=!r}"
Out[32]: 'the_object=datetime.datetime(2021, 1, 24, 21, 12, 23, 550361)'

In [33]: f"{the_object=!s}"
Out[33]: 'the_object=2021-01-24 21:12:23.550361'

In [34]:
```

It would be great to have this in Hy. It looks like this could be handled in `_format_string` in `hy.compiler`, after the handling for format specs. The simple case (`f"{x=}"`) could potentially be handled in place, with the case of a trailing format specification being handled recursively.

Would you consider adding this in spite of it being for Python >=3.8? This is cool - since the parsing is handled by Hy, I think we could make this feature compatible for Hy running on older versions of Python. An example (excuse the clumsy use of pickle to ship the tree around different interpreters, I'm new to `ast`):

```
Python 3.9.1 (default, Dec 13 2020, 11:55:53)

In [97]: tree = ast.parse("print(f'{foo=}')")

In [121]: pickle.dump(tree, open("/home/joshua/test.pickle", "wb"))
```

```
Python 3.6.12 (default, Jan 24 2021, 16:44:51)

>>> tree = pickle.load(open("/home/joshua/test.pickle", "rb"))
>>> tree
<_ast.Module object at 0x7fae44ac09e8>
>>> compile(tree, filename="string", mode="exec")
<code object <module> at 0x7fae44981270, file "string", line 1>
>>> eval(compile(tree, filename="string", mode="exec"))
foo='bar'
```

I'm happy to work on this if it's desirable, and happy for any pointers also.

### PR DESCRIPTION
**Pull request by jams2**
Closes #1948 

I didn't think it was necessary to add documentation as it's part of Python, let me know if you think otherwise.

### CODE REVIEW

**Comment by Kodiologist** [comment]
We do document f-strings, in `syntax.rst`, and that description needs to be updated a bit to account for `=`.

I think the text you put in the docstring would be more helpful as one or more appropriately located comments.

It isn't true that including both a conversion and a format specifier is necessarily a runtime error in Python, nor should it be so in Hy. For example, `f"{2+2!r:5}"` is legal Python, and it can be written in Hy as `f"{(+ 2 2) !r :5}"`.

I believe you can avoid the extra variable `implicit_conversion` by just initializing `conversion` earlier.

**Comment by allison-casey** [comment]
it looks like this is failing for PyPy with
`Pattern "Unknown format code 'f' for object of type 'str'" does not match "Unknown format code f for object of type 'str'"`
It seems that the PyPy throws the same exception just without the single quotes around the `f`. I can't confirm this on my end since pypy is not liking f-strings for some reason on my box, but `pytest.raises` lets you use a regex so this should work just fine.
```clojure
;; Format spec doesn't clobber the explicit conversion.
(with [(pytest.raises
         ValueError
         :match r"Unknown format code '?f'? for object of type 'str'")]
  f"{pi =!s:.3f}")
```

**Comment by jams2** [comment]
Thanks both. I'm not sure how to make this work in the same manner as Python
without the extra variable for `implicit_conversion`. Consider the
following examples:

```python
In [6]: print(py_to_ast('f"{foo=}"'))

Module(
  body=[
    Expr(
      value=JoinedStr(
        values=[
          Constant(value='foo='),
          FormattedValue(
            value=Name(id='foo', ctx=Load()),
            conversion=114)]))],
  type_ignores=[])

```

We used a "=", so the `ast.FormattedValue` gets a conversion value of
114 (repr).

```python
In [74]: print(py_to_ast('f"{foo=!s}"'))

Module(
  body=[
    Expr(
      value=JoinedStr(
        values=[
          Constant(value='foo='),
          FormattedValue(
            value=Name(id='foo', ctx=Load()),
            conversion=115)]))],
  type_ignores=[])
```

A specific conversion, so the AST reflects this (115).

```python
In [75]: print(py_to_ast('f"{foo=:.2}"'))

Module(
  body=[
    Expr(
      value=JoinedStr(
        values=[
          Constant(value='foo='),
          FormattedValue(
            value=Name(id='foo', ctx=Load()),
            conversion=-1,
            format_spec=JoinedStr(
              values=[
                Constant(value='.2')]))]))],
  type_ignores=[])
```

Here, we used "=", but also a format spec, so the FormattedValue's
conversion is set to -1.

```python
In [79]: print(py_to_ast('f"{foo=!r:.2f}"'))

Module(
  body=[
    Expr(
      value=JoinedStr(
        values=[
          Constant(value='foo='),
          FormattedValue(
            value=Name(id='foo', ctx=Load()),
            conversion=115,
            format_spec=JoinedStr(
              values=[
                Constant(value='.2f')]))]))],
  type_ignores=[])
```

In this example, we wrote a format spec, but we can't set the
conversion to -1 as that would clobber the explicitly specified
conversion. Coincidentally this would raise an error at runtime, but
as you rightly pointed out not all combinations of a conversion and a
format spec will cause this. To match Python's behaviour we have to be
able to parse any combination of "=", explicit conversion, and format
spec, bearing in mind that:

1. using "=" will set the conversion to 114 if no explicit conversion
   and no format spec; and
2. a format spec with no explicit conversion will set the conversion
   to -1.
   
The problem I'm having with using the one variable to track the
conversion is that we don't know if it was set implicitly (by the
presence of a "=") or explicitly. We could check if there was a "="
(`if eq_sign_match:...`)  but that doesn't help discern between the
automatic 114 and an explicit setting. Am I missing something?

**Comment by Kodiologist** [comment]
Take a look at the attempt that I pushed. It seems to pass your tests.

**Comment by allison-casey** [comment]
While I like the simplification of removing `implicit_conversion`, inlining 
```python
values.append(HyString(replacement_field_memo[:
               replacement_field_memo.find(eq_sign_match.group())
               + len(eq_sign_match.group())]))
```
Feels like an oversimplifications that makes what's happening less immediately apparent. 

```python
 debug_str_end = (
     replacement_field_memo.find(eq_sign_match.group())
     + len(eq_sign_match.group())
 )
 values.append(HyString(replacement_field_memo[:debug_str_end]))
```
I find this to be much easier to understand at a glance. Is there a reason for this kind of inlining other than conciseness?

**Comment by Kodiologist** [comment]
I find it easier to digest code that's more functional and less imperative, and doesn't oblige the reader to keep track of more names than necessary. But it's a matter of taste.

**Comment by jams2** [comment]
Ok cool, it took me a minute to get my head around this but it looks like you've covered all the cases. I like seeing a different angle on a problem. I agree with @allison-casey that readability suffers a little without the interim variable (I generally prefer to err on the side of being over-descriptive), but I suppose it would be more in keeping with the existing style to inline it.

**Comment by allison-casey** [comment]
> I find it easier to digest code that's more functional and less imperative, and doesn't oblige the reader to keep track of more names than necessary. But it's a matter of taste.

I generally agree as well. For something like this though with two logically distinct operations i would err on the side of the readability of the intermediate variable. Up to you though, as jams2 said, it would be more in keeping with the existing style.

**Review by Kodiologist — APPROVED** [review]

**Comment by scauligi** [comment]
Might I suggest this patch? Using `.find()` is unnecessary, and this also makes the intent (recovering the parsed form itself) a little more clear IMO.

```diff
--- a/hy/lex/parser.py
+++ b/hy/lex/parser.py
@@ -280,13 +280,14 @@ def _format_string(state, p, rest, allow_recursion=True):
        if not match:
           raise LexException.from_lexer('f-string: mismatched braces', state, p[0])
        item = rest[: match.end() - 1]
-       replacement_field_memo = item  # In case we have '=' syntax
        rest = rest[match.end() :]
 
        # Parse the first form.
        try:
            from . import parse_one_thing
-           model, item = parse_one_thing(item)
+           model, remainder = parse_one_thing(item)
+           parsed_form = item[:-len(remainder)]
+           item = remainder
        except LexException:
            raise
        except ValueError as e:
@@ -296,12 +297,9 @@ def _format_string(state, p, rest, allow_recursion=True):
        # Check for '=' debugging syntax, reproduce whitespace in output
        eq_sign_match = re.match(r'\s*=\s*', item)
        if eq_sign_match:
-           values.append(HyString(replacement_field_memo[:
-               replacement_field_memo.find(eq_sign_match.group())
-               + len(eq_sign_match.group())]))
+           values.append(HyString(parsed_form + eq_sign_match.group()))
            item = item[eq_sign_match.end():]
        else:
            item = item.lstrip()
```

**Comment by jams2** [comment]
What do you think about naming `parsed_form` as `f_expression`, so it matches the grammar?

**Comment by allison-casey** [comment]
> Might I suggest this patch?

I like it. Went ahead and changed it. Are we all happy with this? If so, i'll go ahead and approve and merge

**Review by allison-casey — APPROVED** [review]

**Comment by allison-casey** [comment]
Thanks @jams2! :tada: :tada:

**Pull request merged**
