### PR TITLE
Run file using hy -i

### PR DESCRIPTION
**Pull request by NathanW2**
Add support for running a file using `hy -i`

Using a `os.path` check might be a bit of a hack way. Thoughts?

### CODE REVIEW

**Comment by NathanW2** [comment]
If this looks good I can add a unit test for it.

**Comment by NathanW2** [comment]
Added a unit test. Created a new test_files folder with a test file that gets run.

**Comment by berkerpeksag** [comment]
I didn't know `python -i file.py` works too. +1 for being consistent with `python`.

Could you also fix PEP 8 errors?

**Comment by NathanW2** [comment]
No worries. Fixed those pep8 errors.  Just going to see what travis says. The tests pass on my machine.

**Comment by berkerpeksag** [comment]
LGTM. Could you also squash the commits? Thanks!

**Comment by NathanW2** [comment]
Squashed them real good :P

**Comment by theanalyst** [comment]
LGTM

**Comment by berkerpeksag** [comment]
Thanks!

**Comment by NathanW2** [comment]
Thanks

**Pull request merged**
