### PR TITLE
Report objects when raising type error

### PR DESCRIPTION
**Pull request by tuturto**
Improves error reporting just a tiny bit by including offending objects and thus making debugging easier

### CODE REVIEW

**Comment by Kodiologist** [comment]
It might be better to get the `repr`s (`r!`) than the stringifications. Also, you don't need the numbers in the format string.

**Comment by tuturto** [comment]
good catch, should be better now

**Comment by kirbyfan64** [comment]
I just squashed + merged.

**Comment by vodik** [comment]
@tuturto heads up in case you didn't know, `"{!r}".format(foo)` does repr (and `!s` forces str, which is the default).

**Pull request merged**
