### PR TITLE
Set up autoformatting of Python source

### LINKED ISSUE #1704: Internal Python Code Formatting
Anyone interested in handing over all Hy internal Python code formatting to something automated&mdash;like [`black`](https://github.com/ambv/black)?  Would definitely streamline some of the dev process!

### PR DESCRIPTION
**Pull request by lafrenierejm**
Autoformat all Python source code via isort and black. Also add a GitHub Actions check so PRs that do not comply with the autoformatting rules will show a CI failure.

Closes #1704.

### CODE REVIEW

**Comment by lafrenierejm** [comment]
I see the failed checks. I'll look into whether they can be resolved. Worst case I can remove `pyproject.toml` and set the configurations via other means.

**Comment by Kodiologist** [comment]
I'm still against autoformatting, a la Black. I'm sure lots of the formatting in this codebase could be better, but autoformatting throws the baby out with the bathwater.

isort seems far less drastic, but it's hard to see the motivation. What does it matter whether modules are imported in alphabetical order or not? (The author says "I wrote isort because in an organization I used to work in the manager came in one day and decided all code must have alphabetically sorted imports", which exemplifies the uselessness of managers.) Removing old imports that have no effect would be useful, but isort doesn't do that, does it?

**Comment by lafrenierejm** [comment]
> What does it matter whether modules are imported in alphabetical order or not?

The only real benefit to `isort` IMO is reducing noise in diffs going forward. If autoformatting the code itself is not on the table, though, then there's is no reason to adopt `isort`; I could only see `isort` being a nuisance if attempted to enforce it alone.

**Comment by Kodiologist** [comment]
It's not clear to me how it would reduce diff noise. But if you think it's not worth having without Black, then yeah, let's not worry about it.

**Comment by lafrenierejm** [comment]
So to be clear, is it the maintainers' stance that autoformatting will _not_ be adopted? If so, can #1704 be closed with that statement?

CC: @allison-casey, @refi64, @brandonwillard

**Comment by Kodiologist** [comment]
It's my stance, but the others can speak for themselves. You would need two approvals to merge this. If this PR fails, yeah, might as well close the issue.

**Comment by allison-casey** [comment]
I still maintain that pre-commit formatting is a huge benefit on collaborative projects and it's been used to great effect on many other, much larger, python projects. Black's formatting is good enough, is designed to make the smallest possible diffs, and provides consistency and predictability to code bases. It may not be your preferred formatting, but neither was it exactly mine. The benefits on collaborative projects of never having to discuss syntax again and being able to create assumptions around how code is going to look outweighs any of the stylistic nitpicks I have with black. 

If i'm in the minority opinion among maintainers on this that's fine, but I will happily put my yes vote to this PR.

**Comment by lafrenierejm** [comment]
Looks like there are some failures specific to the Windows tests. I'm glad to dig into those if, collectively, autoformatting is desired.

@paultag, @Kodiologist, @allison-casey It's not clear to me who exactly Hy's current maintainers are or what the process for decision-making is. If there's a process I should be following for tagging people or otherwise facilitating this discussion, please LMK.

**Comment by Kodiologist** [comment]
> It's not clear to me who exactly Hy's current maintainers are

An old list of the core team is in `hacking.rst`. The real list is managed as a team in the GitHub organization "hylang". Even then, not everybody on the core team is actually active. That's up to them. Your best bet is an empirical approach, by checking who's reviewed and closed PRs recently.

> or what the process for decision-making is

The merge rules are in `CONTRIBUTING.rst`, section "The PR itself", which is transcluded into `hacking.rst` here [here](https://docs.hylang.org/en/master/hacking.html#the-pr-itself).

> If there's a process I should be following for tagging people or otherwise facilitating this discussion, please LMK.

All you need to do is open a PR and respond to questions, as you've already done. I'd recommend against tagging.

**Comment by lafrenierejm** [comment]
@allison-casey, @brandonwillard I have force-pushed fixes to the test failure. The windows build was doing some… interesting things when I added `pyproject.toml`. I didn't see an obvious fix, so for now I just removed `pyproject.toml` and continued using per-tool configuration files.

I also went ahead and added a new contributing section with the following statement:
> No PR may be merged if it fails that check.

That is my personal preference and my recommendation to maintain consistent formatting, but I'm glad to revise if desired.

**Review by brandonwillard — APPROVED** [review]

**Comment by Kodiologist** [comment]
Oh dear. I didn't think this PR had much of a chance, but now the tables have turned, so I am reduced to begging.

@lafrenierejm Please withdraw this PR. Evidently nobody but me thinks that human choices about formatting are valuable, so instead, consider the asymmetry of the situation. If you don't like the hand-selected formatting of some Python code in this repository, you can always run Black locally. If autoformatting is enforced, on the other hand, you don't have the option of getting to see what code would have looked like had it been formatted by somebody who was thinking about what the code meant and how it would be most clearly expressed. I've been working on Hy for somewhat over 5 years and all my formatting choices will be gone: not gone from the history, but gone from any future commits, and not because somebody found a better way to format a given construct, but because it was decided that custom formatting is only a distraction. Moreover, you're autoformatting all future code as well as all the existing code, so I'm not only losing all my existing formatting; I also won't be allowed to add any in the future.

The situation is analogous to that of machine obfuscation or minimization. Obfuscators can easily replace human-chosen variable names with short systematic names, but the reverse operation isn't so easy. I've seen some pretty clever JavaScript deobfuscators that try to give variables meaningful names, but computer-inferred names are never going to be as informative as good human-selected names, so deobfuscation will never be as good as having the original untouched source.

**Comment by lafrenierejm** [comment]
> Please withdraw this PR.

My stance is that it isn't really my place to withdraw the PR. I feel it is up to Hy's maintainers to decide whether to accept, reject, or leave this PR open.

Clearly this is a change that I personally think would be beneficial, hence my opening the PR to begin with. I agree with the reasoning put forward in the linked issue, so I'll refer to that instead of restating the arguments here.

That said, I recognize that not everyone is convinced by those arguments. It is _not_ my intent to ignore or invalidate the objections; I recognize that at some point formatting is fundamentally a personal preference.

I have far less of a stake in Hy than others here, and I would not be offended at all if this PR were to be closed or just left open indefinitely pending further discussion. If further input from me is wanted, please let me know and I'm glad to provide it. Otherwise I will trust the maintainers to continue stewarding this project however you all think best. :)

**Comment by Kodiologist** [comment]
> My stance is that it isn't really my place to withdraw the PR.

It is your place, and your choice. That's why I asked you to do it, because that's the most I can do now.

**Comment by allison-casey** [comment]
A codebase should be consistent, understandable, and be intuitive for new users. A big part of that is having a consistent style. Black is a stable, battle tested, and trusted formatter used by numerous massive projects to great success in addressing that issue. The question of style on collaborative projects is a question detached from content, a roadblock to meaningful discussion of implementation, and a barrier to new contributors. It's a question we shouldn't have to ask.

**Review by allison-casey — APPROVED** [review]

**Comment by lafrenierejm** [comment]
@allison-casey, @brandonwillard I have rebased the changes. Can this be merged, or is anything else needed from my end?

**Comment by allison-casey** [comment]
Sorry for the delay @lafrenierejm 

1. add a minimal `.pre-commit-config.yaml` file with the black, isort, and default whitespace/eof hooks (you can use pandas config as an example) and mention its as an *optional* tool to conform with the formatting rules in both the `Code Formatting` section of `CONTRIBUTING` and at the end of the `Hacking on Hy` section of `hacking.rst`. Make sure it excludes the `docs` folder with `exclude: '^docs/'`
2. Rebase off master 
3. add a `.git-blame-ignore-revs` file with the commit hash of the bulk format commit
 
and we should be good to go. thanks for all the hard work!

**Comment by lafrenierejm** [comment]
@allison-casey Changes have been made! A rendered version of the updated hacking.rst is viewable at https://github.com/lafrenierejm/hy/blob/autoformatting/docs/hacking.rst.

**Comment by allison-casey** [comment]
Fantastic! `pre-commit run --all-files` does not run clean right now. (looks like some ancillary stuff outside of `hy` and `tests` had issues with new lines and such) run it, squash it, and we'll be all good here :heart:

**Comment by lafrenierejm** [comment]
> `pre-commit run --all-files` does not run clean right now.

Thanks for catching that! It should be all good now.

**Pull request merged**
