### PR TITLE
Added (last) function to core language

### PR DESCRIPTION
**Pull request by acron0**
Hi,

This is my first PR (hopefully of many). I'm going to be working with Hy in production over the next few months and so will be hopefully be able to feed back any features I work on.

This particular addition is trivially small, but a chance to say 'hello' :cake:

### CODE REVIEW

**Comment by microamp** [comment]
Hello, thanks for the contribution! Hy in production for a few months?

**Comment by berkerpeksag** [comment]
LGTM. Could you add documentation and add your name to AUTHORS?

**Comment by microamp** [comment]
It's because ``len`` would only work with strict collections (e.g. ``list``).

**Comment by tuturto** [comment]
Using ```last``` with generator will consume all the generated values, with no way getting them back. Sounds quite rare case to me when it would be useful. But on the other hand, it would be nice if collections and generators/iterators would work in a similar way.

So, I'm leaning towards that ```last``` should work with iterators and generators too. What are other opinions about this?

**Comment by Willyfrog** [comment]
@tuturto you could `tee` the iterator and consume the duplicated one

**Comment by microamp** [comment]
@tuturto @Willyfrog

That's similar to the approach I took when implementing [`drop-last`](https://github.com/microamp/hy/commit/7f5c8e39d8d34acabe476d35f7a2ef71904b5571). Also, I just remembered that the previous version of `butlast`(fixed [here](https://github.com/hylang/hy/commit/23f31d4ac1ac72ca13005bea218b9c2363fa940e)) wasn't working with generators/iterators because of the `len` issue mentioned above.

Your thought on this, @paultag?

**Comment by acron0** [comment]
Proposed alternative: https://www.refheap.com/98654

Tested with:
`=> (last (take 5 (itertools.count 10)))`
`14L`

**Comment by nicolas-p** [comment]
I recently wrote some code for which I needed `first` and `last`. I had to import `last` from Toolz. So I think it would be a useful addition to Hy.

**Comment by microamp** [comment]
@acron0 

My apologies on getting back to you late.

I'd go with the second implementation (the one with ``(list coll)``). I realised that ``itertools.tee`` is irrelevant here since it doesn't stop the original iterable from being exhausted anyway. It is the case with ``butlast`` too.

Mind doing another commit for this when you can?

By the way, you can do something like ``(get aslist -1)`` (think of it as Python's ``aslist[-1]``) instead of having to reverse the collection (then get the first item).

**Comment by acron0** [comment]
Changes are committed. It's obscenely simple now :P

**Comment by microamp** [comment]
+1 from me

We'll wait for one more vote to get it merged since the implementation is now a bit different from what @berkerpeksag signed off previously.

**Comment by berkerpeksag** [comment]
LGTM.

**Comment by berkerpeksag** [comment]
Thanks @acron0 :)

**Comment by acron0** [comment]
Thank you folks! Great to see such a positive, engaging team.

**Comment by paultag** [comment]
Nice work, y'all!

And, thanks Antony!

On Wed, Apr 8, 2015 at 3:02 AM, Antony <notifications@github.com> wrote:

> Thank you folks! Great to see such a positive, engaging team.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/pull/782#issuecomment-90824741>.
>



-- 
:wq

**Pull request merged**
