### PR TITLE
Add import anaphoric macros info

### PR DESCRIPTION
**Pull request by endrebak**
See https://github.com/hylang/hy/issues/965

I'm not used to using git collaboratively, so this might blow up your repo for all I know.

### CODE REVIEW

**Comment by Foxboron** [comment]
I'd love if you could backtick the require word.

**Comment by Foxboron** [comment]
<3 Awesome work!

**Comment by gilch** [comment]
Squashing the minor fixes into the first commit would be good. We like to keep minor fixes like that out of master to make it easier to navigate.

In case you're not familiar with the git command line, make sure you have this branch checked out and use `git rebase -i HEAD~3` to squash them into one commit, then `git push origin anaphoric-import-info-missing --force` to make your github branch match your local repo so we can merge it.

**Comment by endrebak** [comment]
```endrebakkenstovner@endres-MBP ~/c/endre-hy ((f053055...))> git rebase -i HEAD~3
Successfully rebased and updated detached HEAD.
endrebakkenstovner@endres-MBP ~/c/endre-hy ((f053055...))> git push origin anaphoric-import-info-missing --force
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:endrebak/hy.git
 + f053055...633e660 anaphoric-import-info-missing -> anaphoric-import-info-missing (forced update)
```

Still seems there are two commits above, perhaps I failed?

**Comment by endrebak** [comment]
```
endrebakkenstovner@endres-MBP ~/c/endre-hy ((f053055...))> git rebase -i HEAD~3
Successfully rebased and updated detached HEAD.
endrebakkenstovner@endres-MBP ~/c/endre-hy ((f053055...))> git push origin anaphoric-import-info-missing --force
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:endrebak/hy.git
 + f053055...633e660 anaphoric-import-info-missing -> anaphoric-import-info-missing (forced update)
```

I still see several commits above though...

**Comment by gilch** [comment]
Looks like one of them squashed though. It should pop up a script for you to edit. The script comments explains how it works: change "pick" to "squash" except for your first commit. Then save the script and git will use it when you close the editor. There's only two commits now, so use `HEAD~2` this time.

**Comment by endrebak** [comment]
Much obliged, did not read the instructions, just quickly copy pasted the commands. (Off to hack on `hy-mode.el` ...)

**Comment by zackmdavis** [comment]
***+1*** :shipit:

**Comment by paultag** [comment]
Yay! Thank you, @endrebak!

**Comment by paultag** [comment]
@hylang/core - can pls add to authors :)

**Pull request merged**
