### PR TITLE
Fix Python 3.5.1 support by converting kwargs and stararg to str as late as possible (thus preserving positional information)

### LINKED ISSUE #995: Failure to add two simple integers on the newly released Python 3.5.1
Observe:
```hy
hy 0.11.0 using CPython(default) 3.5.1 on Linux
=> (+ 2 2)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/hy/compiler.py", line 2278, in hy_compile
    compiler = HyASTCompiler(module_name)
  File "/usr/local/lib/python3.5/site-packages/hy/compiler.py", line 378, in __init__
    load_stdlib()
  File "/usr/local/lib/python3.5/site-packages/hy/compiler.py", line 73, in load_stdlib
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/site-packages/hy/importer.py", line 180, in load_module
    self.path)
  File "/usr/local/lib/python3.5/site-packages/hy/importer.py", line 75, in import_file_to_module
    _ast = import_file_to_ast(fpath, module_name)
  File "/usr/local/lib/python3.5/site-packages/hy/importer.py", line 67, in import_file_to_ast
    return hy_compile(import_file_to_hst(fpath), module_name)
  File "/usr/local/lib/python3.5/site-packages/hy/compiler.py", line 2279, in hy_compile
    result = compiler.compile(tree)
  File "/usr/local/lib/python3.5/site-packages/hy/compiler.py", line 428, in compile
    ret = self.compile_atom(_type, tree)
  File "/usr/local/lib/python3.5/site-packages/hy/compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/usr/local/lib/python3.5/site-packages/hy/compiler.py", line 596, in compile_raw_list
    ret = self._compile_branch(entries)
  File "/usr/local/lib/python3.5/site-packages/hy/compiler.py", line 483, in _compile_branch
    return _branch(self.compile(expr) for expr in exprs)
  File "/usr/local/lib/python3.5/site-packages/hy/compiler.py", line 313, in _branch
    results = list(results)
  File "/usr/local/lib/python3.5/site-packages/hy/compiler.py", line 483, in <genexpr>
    return _branch(self.compile(expr) for expr in exprs)
  File "/usr/local/lib/python3.5/site-packages/hy/compiler.py", line 440, in compile
    raise_empty(HyCompileError, e, sys.exc_info()[2])
  File "<string>", line 1, in raise_empty
hy.errors.HyCompileError: Internal Compiler Bug 😱
⤷ TypeError: required field "lineno" missing from arg
Compilation traceback:
File "/usr/local/lib/python3.5/site-packages/hy/compiler.py", line 428, in compile
    ret = self.compile_atom(_type, tree)
  File "/usr/local/lib/python3.5/site-packages/hy/compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/usr/local/lib/python3.5/site-packages/hy/compiler.py", line 1767, in compile_expression
    expression = macroexpand(expression, self.module_name)
  File "/usr/local/lib/python3.5/site-packages/hy/macros.py", line 170, in macroexpand
    load_macros(module_name)
  File "/usr/local/lib/python3.5/site-packages/hy/macros.py", line 154, in load_macros
    _import(module)
  File "/usr/local/lib/python3.5/site-packages/hy/macros.py", line 151, in _import
    __import__(module)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/site-packages/hy/importer.py", line 180, in load_module
    self.path)
  File "/usr/local/lib/python3.5/site-packages/hy/importer.py", line 78, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "/usr/local/lib/python3.5/site-packages/hy/importer.py", line 43, in ast_compile
    return compile(ast, filename, mode, flags)
=> 
```

I'll be testing `master` (instead of 0.11.0) in a moment, but figured this was worth filing an issue about regardless in case we need to push 0.11.1 or something (if it is already fixed in master).

### PR DESCRIPTION
**Pull request by tianon**
Fixes #995

### CODE REVIEW

**Comment by tianon** [comment]
Wooot, green CI now. :smile:

**Comment by paultag** [comment]
Seems good to me! Has ACK. RFR @hylang/core

**Comment by zackmdavis** [comment]
> green CI now.

Note that CI is still [only testing 3.5.0](https://travis-ci.org/hylang/hy/jobs/95708603). But I just built 3.5.1 and can confirm that your fix works. :shipit:

**Comment by tianon** [comment]
@zackmdavis yeah, I had a few rounds beforehand where I'd broken 2.7 and 3.3 :innocent:

**Comment by zackmdavis** [comment]
@tianon right, I should have inferred from context that previous work had been squashed.

**Pull request merged**
