### PR TITLE
Docs: Hy <-> Python interop fix #1061

### LINKED ISSUE #1061: Add a section in the docs about using Hy from Python.
This doesn't seem to be explained very well. My understanding is that you can
- `import hy` in a Python script and then import modules written in Hy. Naturally, Hy must have been installed for this to work.
- create a Python module `foo` with an `__init__.py` that does the `import hy`, and then just `import foo`. (Hy must still have been installed. I think.)
- compile with `hyc` and get a normal `.pyc` file. Import said `.pyc`. Does this still work? Do you have to install Hy too, or does the `.pyc` include that?

I didn't see _any_ of this in the docs.

What if I want to `eval` (`exec`?) a string containing Hy code? Is there a way to do that from Python? Or can you only `import`? Can I launch a Hy repl from Python's? These capabilities are important for supporting doctest #1019. If these capabilities exist, they should be documented. If not, they should be added.

### PR DESCRIPTION
**Pull request by Ealhad**
I separated the existing text in two sections, with some additional explanations and a link to Hy's `import`.

### CODE REVIEW

**Comment by Kodiologist** [comment]
> You can also compile your module with `hyc`. Then you can import it directly (Hy still has to be installed)

This isn't always true. If you edit the example `greetings` module by renaming the parameter `name` to `addressee`, then the resulting `greetings.pyc` no longer requires Hy. Using `name` makes Hy add `from hy.core.language import name` at the top of the file because `name` happens to be the name of a builtin. (Is this a bug or an unavoidable limitation of Hy? It's not obvious to me.)

More generally, I think that fulfilling #1061 calls for adding discussion of lots of gory details. Your additions here don't suffice. @gilch filed that issue, so maybe he can chime in.

It looks like this is your first pull request. Please don't be scared away by how I've received it; we do need more contributors, to both the code and the documentation. Thanks for pitching in.

**Comment by Ealhad** [comment]
First PR indeed, not scared away 😬 

> More generally, I think that fulfilling #1061 calls for adding discussion of lots of gory details. Your additions here don't suffice.

In that case, maybe this should be completely moved away from the tutorial, which would still contain general interop instructions without the “gory details”.

What I have understood so far is that if anywhere in the code, the name of a Hy builtin is found, it is imported.
For example :
```
(def second 42)
```
triggers 
```
from hy.core.language import second
```

**Comment by Kodiologist** [comment]
> In that case, maybe this should be completely moved away from the tutorial, which would still contain general interop instructions without the "gory details".

Yeah, that makes sense to me. We've generally agreed that the tutorial should be fairly short so it isn't too intimidating.

> What I have understood so far is that if anywhere in the code, the name of a Hy builtin is found, it is imported.

I think that's how it works, yeah. I've never read the part of the codebase that does this.

**Comment by Kodiologist** [comment]
Oh, and don't forget to add yourself to AUTHORS.

**Comment by Kodiologist** [comment]
> I'd suggest documenting mangling in a separate PR.

Although, you may not want to do this now since mangling may change soon (#1173, #1115), anyway.

**Comment by Ealhad** [comment]
Thank you for those words! (tssst, I wanted to put a space before my exclamation mark. It’s hard being French when writing in English)
I’ll make the corrections quickly.

    I'd suggest documenting mangling in a separate PR.
Shouldn’t mangling still be mentioned in this section? Maybe a link would suffice.

**Comment by Kodiologist** [comment]
Yeah, a link would make sense.

**Pull request merged**
