### PR TITLE
Fix non-interactive with param -i in subprocess

### PR DESCRIPTION
**Pull request by a690700752**
continue #2555 .
When I use the -i parameter to force the launch of the REPL and send code in subprocess (using nvim conjure), it directly enters the repl.runsource block for execution and never enters repl.run(). In this case, the current environment is not the REPL environment, lacking the PS1, PS2 prompts, and some other REPL-specific environment settings, which contradicts the meaning of the -i parameter. On the other hand, other branches execute code first, such as from a file, before entering repl.run().

### CODE REVIEW

**Comment by Kodiologist** [comment]
The test is a bit wonky. Giving the `default` argument to `getattr` means that you're accepting either of `sys.ps1` or `sys.flags.interactive`. Shouldn't you be more specific as to which you expect, or simply test for both?

**Comment by a690700752** [comment]
There just a tests result, below is the result. Maybe we can add comment to that test code.

| Environment                                 | IPython | PyCharm Console | Shell (run Python, paste code) | Jupyter Notebook | PyCharm Run | PyCharm Run (Emulate terminal) | Shell (run Python file) |
| ------------------------------------------- | ------- | --------------- | ------------------------------ | ---------------- | ----------- | ------------------------------ | ----------------------- |
| Expected Value                              | TRUE    | TRUE            | TRUE                           | TRUE             | FALSE       | FALSE                          | FALSE                   |
| hasattr(sys,'ps1')                          | TRUE    | TRUE            | TRUE                           | TRUE             | FALSE       | FALSE                          | FALSE                   |
| hasattr(sys,'ps2')                          | TRUE    | TRUE            | TRUE                           | TRUE             | FALSE       | FALSE                          | FALSE                   |
| sys.\_\_stdin\_\_.isatty()                  | TRUE    | FALSE           | TRUE                           | FALSE            | FALSE       | TRUE                           | TRUE                    |
| sys.\_\_stdout\_\_.isatty()                 | TRUE    | FALSE           | TRUE                           | TRUE             | FALSE       | TRUE                           | TRUE                    |
| hasattr(\_\_builtins\_\_,'\_\_IPYTHON\_\_') | TRUE    | FALSE           | FALSE                          | TRUE             | FALSE       | FALSE                          | FALSE                   |
| not hasattr(\_\_main\*\*, '\_\_file\_\_')   | TRUE    | FALSE           | TRUE                           | TRUE             | FALSE       | FALSE                          | TRUE                    |
| bool(sys.flags.interactive)                 | FALSE   | FALSE           | FALSE                          | FALSE            | FALSE       | FALSE                          | FALSE                   |

**Comment by Kodiologist** [comment]
That's an impressive table you've compiled, but your test only checks `hy -i`, so that's what the assertion should be written for.

**Comment by a690700752** [comment]
Ok, I'll continue finish tests.

**Comment by Kodiologist** [comment]
How's this going?

**Comment by Kodiologist** [comment]
Superseded by #2587.

**Pull request closed without merging**
