### PR TITLE
Mangling makeover

### LINKED ISSUE #360: Find a way to keep the "original" symbol before the interop munging
``` clj
=> 'foo?
u'is_foo'
```

I think it'd be worthwhile to keep the original symbol, as it could be useful in pure hy stuff (typically printing quoted Hy expressions).

One way to do that would be to move all the munging to `HySymbol`'s `__init__`, and keep the original as an attribute.

### LINKED ISSUE #970: add option to hy2py that converts symbols to valid python identifiers
Hy would be more useful if it could compile to Python, and not just ast, see #923.

`hy2py` can translate ast back into Python source. It's very useful as a debugging tool, but the result is not always executable. The main issue seems to be that Hy identifiers are a superset of valid Python identifiers. The ast doesn't care, but when importing Hy from Python we have a system to resolve this problem using Punycode and a few other rules (`-` to `_` etc.)

I'm proposing we add an option to `hy2py` that converts all invalid symbols using the same system. This way the Python code will be still be executable. I'm not sure if there are other problems with the output, but it's a step in the right direction.

This might also be more useful as the default for `hy --spy`.

### LINKED ISSUE #1115: clean up rules for `?`
Hy converts a trailing `?` to an `is_` prefix. This means that you can use a more lispy style for common predicate methods:

``` Hy
=> (.integer? 1.0)
1.0.is_integer()
True
=> (.integer? 1.5)
1.5.is_integer()
False
```

But due to an unfortunate inconsistency in Python's naming conventions, it doesn't always work:

``` Hy
=> (.lower? "foo")
'foo'.is_lower()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'str' object has no attribute 'is_lower'
=> (.islower "foo")
'foo'.islower()
True
```

There's no underscore in `islower`! This appears to be the case for all string predicate methods. It may also be true elsewhere in the Python standard library, and therefore in other Python libraries.

We may be able to adjust the rules to make this more consistent.
### ~~option 1~~

Make a prefixed `?` become a prefix `is`.

``` Hy
=> (.?lower "foo")
'foo'.islower()
True
```

This way, we can leave the suffix case (and any code using it) as-`is_`. But now there's three ways to write `is_integer`, `?-integer`, and `integer?`.
### ~~option 2~~

Make a suffix `?` become a prefix `is` and suffix `-?` become a prefix `is_`.

``` Hy
=> (.integer-? 1.0)
1.0.is_integer()
=> (.lower? "foo")
'foo'.islower()
```

This can break existing Hy code, but we're doing that anyway.
### option 3

Remove the special treatment of `?`. Use the same names in Hy as in Python. Hy becomes more consistent and less magical. Hy names ending in `?` become as difficult to use in Python as Hy names with an embedded `?` are now. But it's still possible with `getattr`.

We could probably come up with more options, but in any case, it needs to be documented. I didn't see the current `?` rule in the docs either.

### LINKED ISSUE #1168: Should keywords be mangled?
By "mangled", I mean having hyphens changed to underscores, `:foo?` changed to `:is_foo`, etc.

I'm inclined to say yes, because keywords are supposed to be a kind of symbol, and we mangle ordinary symbols. Currently, keywords aren't mangled.

### LINKED ISSUE #1173: Rethink mangling
Python since version 3.0 allows much of Unicode in its identifiers. Hy's punycode mangling therefore serves no purpose but to make Unicode identifiers harder to read and Hy-Python interop more difficult. Maybe we should remove this "feature" altogether.

Some Hy features are already restricted to Python 3 or later. Unicode identifiers could be another such feature. It's probably a minority of users that need Python 2 support at this point anyway (and this will only become more true over time). They'll be able to make do with ASCII.

On the other hand, mangling of ASCII characters can be improved. Hy already converts `-` to `_`, to allow more Lispy names. Hy code would look very different without this, but it does cause some problems.

The other rules are even worse. The earmuff conversion to all caps is of dubious value. It usually indicates a dynamic variable in Lisp, but Hy doesn't have those. (maybe we could add them #1089) I'd like to remove it.

Hy also converts a trailing `!` to trailing `_bang` and a trailing `?` to a leading `is_`. But if these characters appear anywhere else, they don't get converted. The AST mostly doesn't care when the results are not valid Python identifiers, but we have no guarantee this will continue. It's already been an issue for `getargspec` #1172 . There are other ASCII characters that are allowed in Hy symbols (like `+`) but never get converted at all.

Clojure also has to use Java identifiers, but it has a [more consistent approach](https://clojuredocs.org/clojure.core/munge) that we might consider emulating. Java's identifier rules are almost as strict as Python 2.

### LINKED ISSUE #1336: add mangle function to public api
This only exists internally in the Python, but it's important for writing macros. Clojure, for example, [exposes `munge` in its core](https://clojuredocs.org/clojure.core/munge) namespace.

### PR DESCRIPTION
**Pull request by Kodiologist**
- Closes #360
- Closes #970 (no longer necessary)
- Closes #1115 (debatably)
- Closes #1168 (keywords are now indeed mangled when used for keyword arguments)
- Closes #1173 (or at least, changes the situation drastically)

This pull request overhauls mangling such that HySymbols remember their original names (it is no longer the case that `(= 'a-b 'a_b)`) and all Python variables have names that are legal Python identifiers. The latter accomplishes most of what we need to ensure that `hy2py` produces real Python code.

The major changes are:

- Mangling happens at compile-time, not read-time.
- Mangling rules are different.
  - `*foo*` → `FOO` and `foo!` → `foo_bang` are gone.
    - The first one seems misleading, and the second rarely useful.
  - The Punycode transformation (which was only enabled for Python 2 anyway) is gone.
  - `foo-bar` → `foo_bar` and `foo?` → `is_foo` remain.
  - Names that still aren't legal Python identifiers (either because they contain illegal characters or because they coincide with a Python reserved word) are prepended with `hyx_`, and each illegal character is replaced with `ΔfooΔ` (or for Python 2, `XfooX`), where `foo` is the Unicode character name in lowercase with spaces replaced by underscores and hyphens replaced by "H"es. If the character doesn't have a name, we use "U" followed by its code point in lowercase hexadecimal.
  - Any added `hyx_` or `is_` is added after any leading underscores (because leading underscores can have magical effects in Python).
- The names of keyword arguments are fully mangled.

The below things remain to be done, but I figured I'd get feeback before continuing.

- [ ] Watch out if the REPL variable `_` is confused with the shadow subtraction operator `-`
- [ ] In the unmangle function, undo `hyx_` when necessary; otherwise, the distinct variables "hyx_X61X" and "a" will both unmangle to "a"
- [ ] Perhaps make the mangle function stringify the input, so the caller doesn't have to
- [ ] Rename the mangling functions `mangle` and `unmangle` and add them to core (fixes #1336)
  - [ ] Testing
  - [ ] Documentation
- [ ] Document mangling in general
- [ ] Use `unmangle` instead of `hyify` in core
- [ ] NEWS

### CODE REVIEW

**Comment by Kodiologist** [comment]
By the way, some of the underscore-to-hyphen edits in "Mangle symbols at compile-time instead of parse-time", particularly in `@build(...)` expressions, can be undone if desired, thanks to the later commit that mangles the names of special forms.

**Comment by gilch** [comment]
I tried a few symbols, and I think legibility is a problem, especially for gensyms. I thought about how we could change how we construct the gensym names and realized that it's better to change the mangling system.

For example, the gensym `Hy, world` mangles as
`_hyx_X3bXHyX2cXX20XworldX7cX1240`.

But I think we could instead mangle it to something like
`_hyx_3B2C207C_XHyXXworldX1239`
which is much more readable. Here I've moved all the hexidecimal codes to the front, and then replaced the invalid characters with a single `X` each. The unmangle function could put them back together like this:
```Python
>>> from base64 import b16decode
>>> '_' + 'XHyXXworldX1239'.replace('X','{}').format(*b16decode('3B2C207C').decode('utf-8'))
'_;Hy, world|1239'
```

**Comment by gilch** [comment]
Actually, it might be even better to use `_` as the elision marker instead of `X`. e.g.
`_hyx_3B2C207C__Hy__world_1239`.
An actual `_` would have a corresponding `5F` in the hex codes.

**Comment by gilch** [comment]
I'm not sure if the `?` to `is_` mangling is worth keeping either, but I'd like to hear what the others think.

We could use `*1 *2 *3` as the repl history variables like Clojure instead of `_`. #1341 

But I am worried about the ambiguity introduced by treating `-` and `_` as the same sometimes, but not other times. It's not reversible. If we don't give `-` special treatment and use my suggested format above, `foo-bar` would render as `hyx_2d_foo_bar`, which is quite legible, but not something you'd want to import in Python. Perhaps when producing things for Python's use you simply write `foo_bar` instead.

Another possibility is to swap `-` with `_` before mangling, and swap them back when unmangling. But this means you must write magic dunder/private names with `-`, which is easily confused with negation. See #1062 for a discussion of why `_` is preferable as a prefix. Perhaps leading and trailing `_` could be special cased (like `?` is now) to avoid this issue but still be reversible.

**Comment by Kodiologist** [comment]
> I thought about how we could change how we construct the gensym names and realized that it's better to change the mangling system.

I do see one way it could make sense to change the gensym format: instead of `_;foobar|1235`, use `_;foobar_1235`. I see why you want the leading underscore (to prevent automatic import) and the `;` (to create an illegal Hy identifier), but you don't need the `|`, right? Then this mangles to `_hyx_X3bXfoobar_1235`, which seems pretty reasonable.

We could also have the `;` do double duty as the digits separator, yielding `_foobar;1235`, which mangles to `_hyx_foobarX3bX1235`.

I think your suggestion of putting Base16 UTF-8 at the beginning works, too, even if we also make one of the aforementioned changes to the gensym format.

> Actually, it might be even better to use `_` as the elision marker instead of `X`.

But `_` is a common identifier character, whereas `X` is uncommon. 

> We could use `*1 *2 *3` as the repl history variables like Clojure instead of `_`.

That sounds reasonable.

**Comment by gilch** [comment]
> But `_` is a common identifier character, whereas X is uncommon.

True, but why does that make X a better choice?

Underscores are more legible than X's.

I use the astor output from `hy --spy` all the time and I need to be able to read the identifiers. It's the one non-alphanumeric character allowed in Python2 identifiers. In the common case, you don't have to encode it anyway, and when you do, it still shows up as an underscore in the part you actually read!

**Comment by gilch** [comment]
> it could make sense to change the gensym

I picked the current gensym format for legibility when debugging macro output with astor. I'd certainly consider improvements to it after we settle the encoding format. But what's best for gensyms depends on that, so let's figure it out later.

>  undo hyx_ when necessary

I think it makes sense to treat a symbol containing a `hyx__` prefix like an illegal identifier. That is, encode it again. It's just like double-escaping backslashes. So `hyx__foo` might be encoded as `hyx__hyx__foo`. Make it a 1:1 invertable function, so there would always be an unambiguous unmangling for any identifier.

**Comment by Kodiologist** [comment]
> True, but why does that make X a better choice?

1. Because it means fewer characters have to be escaped. So, `some_l∞ng_identifier` becomes `hyx_E2889E_some_lXng_identifier` instead of `hyx_5FE2889E5F_some_l_ng_identifier`.

2. Because when you see an X in a `hyx_…` symbol, you can be pretty sure it's something else, whereas a `_` is as likely to be a `_` as something else.

Also, not related to the rarity of X, it's easier to count Xes than underscores. (This isn't important for my original proposal, where you never have more than two Xes (or rather, undercoress) in a row, but could become a pain point with your Base16 UTF-8 method.)

> I picked the current gensym format for legibility when debugging macro output with astor. I'd certainly consider improvements to it after we settle the encoding format. But what's best for gensyms depends on that, so let's figure it out later.

Okay, sure.

> I think it makes sense to treat a symbol containing a `hyx__` prefix like an illegal identifier. That is, encode it again.

That was my original plan, but I realized it wouldn't allow you to use the unmangled form in Hy. That is, you can write `foo?` as `is_foo` or `foo-bar` as `foo_bar`, but you wouldn't be able to write an identifier with illegal characters in its pure-ASCII `hyx_` form.

> Make it a 1:1 invertable function, so there would always be an unambiguous unmangling for any identifier.

That would be nice, but we can't have it so long as `foo-bar` and `foo_bar` in Hy both get mangled to `foo_bar`. Which I like and want to keep.

**Comment by gilch** [comment]
> 1. Because it means fewer characters have to be escaped. So, `some_l∞ng_identifier` becomes `hyx_E2889E_some_lXng_identifier` instead of `hyx_5FE2889E5F_some_l_ng_identifier`.

Are you concerned about the greater length when using a common character? 

Because of runtime performance? Identifiers are interned in Python. Length has no effect. 

Because it causes lines to wrap? That's kind of unavoidable with astor, but we could use base64 instead. I preferred base16 because it's easier to lookup the Unicode by hand if necessary, but I don't feel too strongly about it, since we're providing an unmangle function.

Because it's harder to type from Python? Exports to Python should not use such names, but again base64 is an option.

> 2. Because when you see an X in a `hyx_…` symbol, you can be pretty sure it's something else, whereas a `_` is as likely to be a `_` as something else.

And you'd still have to check for a `58` to be sure it's not really an `X`. It's true that `X` is a rare letter in English, but it's a common letter in mathematics, so I'm not sure if it's as uncommon as you think it is in code.

But if that's your concern, wouldn't a rare Unicode character be a better choice? Python2 requries pure ASCII, but we're using different mangling rules for Python3 anyway. To be legible, it ought to be punctuation mark rather than a letter (or at least look that way), but valid in a Python3 identifier. Perhaps U+2054 `⁔`. These are also easier to count than underscores.

Maybe you want Python3 to use pure ASCII too for some reason? I can kind of understand not wanting force anyone to use Unicode in the command-line dubugger. But you can copy/paste identifiers or even the elision character if you're constructing them. You can even use strings and type out `\u2054` in Python.

I'm mainly concerned about losing my readable astor output for debugging.

We could instead avoid forcing Unicode on those who don't use it, but still use it as the elision character. At least for ASCII, we could replace invalid characters with a more mnemonic underscore-quoted substring via lookup table, e.g. `+` with `_plus_` or `_add_` or `_t_`; ` `(space)/`__` or even `_sp_; `?`/`_eh_` or `_qMark_`, etc. Clojure does something similar to make valid Java identifiers. There may be some tradeoff between obviousness and length, but this is much more readable than meaningless hex codes.

Suppose you wanted an increment function named `X+1` and an inverse function named `X-1`. Under the proposals they might look like
* `X+1`/`X-1` (status quo output, but invalid Python)
* `hyx_X58XX2bX1`/`hyx_X58XX2dX1` (X quotes)
* `hyx_582B_XX1`/`hyx_582D_XX1` (X elision)
* `hyx_2B_X_1`/`hyx_2D_X_2` (_ elision)
* `hyx_2B_X⁔1`/`hyx_2D_X⁔2` (⁔ elision)
* `hyx_X_add_1`/`hyx_X_sub_1` (mnemonic lookup table)
Only in the first and last case is the meaning clear, but elision seems easier to read than quotes, and `X` is the least readable of the elision characters.

Perhaps we'd use `⁔` only if there's a non-ASCII invalid character. But the higher Unicode would still have to use the hex codes, since a lookup table that big is probably not worth the trouble. But maybe we could write a program to convert the official Unicode names somehow, e.g. `foo⁔bar` becomes `hyx_foo_InvertedUndertie_bar`. Some of the names are pretty long though.

**Comment by Kodiologist** [comment]
I agree that hexadecimal is a better choice than Base64 for this, whether we're using a quoting method or an elision method.

> It's true that `X` is a rare letter in English, but it's a common letter in mathematics

I don't think it's common as an uppercase letter in a Python identifier, because of how uppercase tends to be used. It also happens to fit with the use of `\x` to quote a character by its hex code.

Using a non-ASCII character is a pretty good idea, though. I don't think we should use `⁔`, because it seems to be some sort of combining character (in Emacs, it's being influenced by characters that I put around it in weird ways), but what about the Greek letter `Δ`?

Using Unicode character names is something that occurred to me but I didn't think about it much. How about, per your implicit suggestion, illegal characters get replaced with a CamelCase version of the name? So the identifier `#` becomes `hyx_ΔNumberSignΔ`, `+` becomes `hyx_ΔPlusSignΔ`, and `some-l∞ng-identifier` becomes `hyx_some_lΔInfinityΔng_identifier`? For a bit of brevity, we could use another `Δ` at the beginning instead of `hyx_`. Thus, `+` becomes `ΔΔPlusSignΔ`.

**Comment by gilch** [comment]
I like where this is going. Using the Unicode names is much more legible in most cases.

Yes, combining characters could be trouble, but I'm not sure if `⁔` is one or not. I like the choice of delta better than X, but perhaps we could find a better one. It makes Greek variable names awkward anyway. A variable named `Δ` would mangle to `ΔΔGreekCapitalLetterDeltaΔ`, I suppose.

Python's `unicodedata` module has both a `name` function and its inverse `lookup`. So we wouldn't have to make our own Unicode table. But not all characters have names. We could make our own names table for the missing ASCII (the first 32 control characters), and fall back to the base16 representation for any nameless higher Unicode.

But Unicode names have spaces, which isn't allowed in identifiers. I figured that the simplest reversible transformation is `.replace(' ', '_')`, which gives e.g. `PLUS_SIGN`. The problem is names with hyphens, like  `LESS-THAN SIGN`. Camel case is also reversible, since Unicode names are all upper case. I had only suggested that so we could use `_` quotes, but we need it for the hyphen. So `<` would probably be `Less_thanSign`. I hope Unicode names don't have any other special characters. We should write a test enumerating all Unicode to make sure everything round-trips anyway though.

**Comment by Kodiologist** [comment]
Oh, gross, I didn't realize that some Unicode characters don't have names. There are aliases, like "NULL" for U+0000, but private-use characters don't even have those. If we use hexadecimal for some characters, then we need a way to distinguish the hex codes from character names. I guess we can use a leading lowercase `x`, because names will always start with a capital letter.

> A variable named `Δ` would mangle to `ΔΔGreekCapitalLetterDeltaΔ`, I suppose.

In Python 3, it's a legal identifier, so it doesn't need mangling.

Speaking of which, Python 2 only allows ASCII in identifiers, so we can't use a non-ASCII escape character. I guess we'll fall back on "X" then, unless you still want to use "_", which would produce things like `hyx_LowLine_some_LowLine_l_Infinity_ng_LowLine_identifier`. 

I've checked that for every Unicode character with a name, the name matches `r"\A[-A-Z0-9 ]+\Z"`. So, are we good with Δ delimiters for Python 3, X delimiters for Python 2, names for characters with names, `x` followed by hex digits for characters without names, and hyphens in names replaced with underscores?

**Comment by gilch** [comment]
Yeah let's go with that for now. I'm not sure of some of the details, but they should be more obvious when the actual code is available to test.

**Comment by gilch** [comment]
Do the Unicode names match `r"\A[-A-Z ]+\Z"` too? That means we could replace `-` with a numeral. We could also count the empty string as `_` as a special case. 
* `hyx__LowLine_some_LowLine_l_Infinity_ng_LowLine_identifier` (_ quotes)
* `hyx__some__l_Infinity_ng__identifier` (empty is `_`)
* `hyx_some_lXInfinityXng_identifier` (X quotes)

`<foo_X>`
* `hyx__Less1ThanSign_foo__X_Greater1ThanSign_` (empty is `_` and `-` is `1`)
* `hyx__Less0ThanSign_foo__X_Greater0ThanSign_` (empty is `_` and `-` is `0`)
* `hyx_XLess_ThanSign_foo_XLatinCapitalLetterXX_Greater_ThanSign_` (X quotes)

The last one doesn't round trip! It worked when using hex codes, since X isn't in `[a-f0-9]`. We can't do X quotes for Python2 like that.

**Comment by Kodiologist** [comment]
> Do the Unicode names match `r"\A[-A-Z ]+\Z"` too? 

Surprisingly, no. Even though digits don't appear in the names of the ASCII digits, they show up in the names of some higher characters.

> The last one doesn't round trip!

Ah, true. X quotes can't work for Python 2 if we're using character names. Nor can we use underscores, since we need those for hyphens in character names. That seems to leave us with my original plan of using hex for every character. I'd rather just use that for Python 3, for simplicity, but if you wouldn't accept that, and you would accept that for Python 2 and delta quoting for Python 3, I'll add delta quoting for Python 3. What do you say?

**Comment by gilch** [comment]
I think we could special-case the empty string for `X`, so `<foo_X> becomes

`hyx_XLess_ThanSign_foo_XX_Greater_ThanSign_`

We could do that for Delta too.

**Comment by Kodiologist** [comment]
But we'd still have the problem of `X` in other names, right? Like U+2423 OPEN BOX, ␣.

**Comment by gilch** [comment]
> OPEN BOX

Ah, good point. Python2 is a pain.

We could try not using camel case. Convert to lower case, replace space with `_`, and `-` with `__`. This could only fail if a Unicode name contains two spaces in a row, which I don't think would ever happen, or if a Unicode name contains space-hyphen or hyphen-space sequence, which might.
`hyx_Xless__than_signXfoo_Xlatin_capital_letter_xXXgreater__than_signX`

If that's a concern, as above, but instead replace `-` with `H` (for "Hyphen").
`hyx_XlessHthan_signXfoo_Xlatin_capital_letter_xXXgreaterHthan_signX`
We converted the name to lower case, so `H` can't appear in the name, and neither can `X`. And `H` conveniently contains the horizontal line just like a hyphen, so it's pretty easy to read.

There are probably other solutions, but what do you think of this?

**Comment by Kodiologist** [comment]
> Python2 is a pain. 

It always is. ;_;

I was 95% sure that space-hyphen and hyphen-space wouldn't occur, but it turns out that a handful of Tibetan letters have them (e.g., U+0F0A, "TIBETAN MARK BKA- SHOG YIG MGO"). So I think we have to go with `H` for hyphens. Then the only way that Python 2's and Python 3's mangling rules will need to be different, other than the fact that Python 2 needs more things escaped to begin with, is that Python 2 will use `X` and Python 3 will use `Δ`. Sound good?

**Comment by gilch** [comment]
Pretty much, but I still want to test the resulting code before final approval.

Also what about the special case `XX` and `ΔΔ` to mean `X` and `Δ`? Otherwise we have to spell out `Xlatin_capital_letter_xX` and `Δgreek_capital_letter_deltaΔ` when there are any other illegal characters.

It seems like a bigger problem for Python2 or Greek speakers. `X` quotes does seem like the best of bad options for Python2. But I'm not sure about the choice of `Δ`. It's legible (at least when you're not writing Greek) and that seems easy to change if someone has a better idea.

**Comment by Kodiologist** [comment]
> I still want to test the resulting code before final approval

Yes, that goes without saying.

> Also what about the special case `XX` and `ΔΔ` to mean `X` and `Δ`?

They're both pretty rare, and it's only an issue when other characters have to be escaped, so the additional mangling rule doesn't seem worth it to me.

**Comment by Kodiologist** [comment]
Rebased. See the edited PR description for the new rules. I used `U` instead of `X` for hexadecimal code points to make parsing easier in the case of Python 2.

**Comment by vodik** [comment]
Looks good to me.

And I don't think the `is_` mangling is worth keeping because Python isn't consistent with `is_foo` or `isfoo`

**Pull request closed without merging**
