### PR TITLE
Add: parse-args function

### PR DESCRIPTION
**Pull request by alphapapa**
I went through the steps in `CONTRIBUTING`, but please let me know if any changes are required.

Thanks for your work on Hy.

### CODE REVIEW

**Comment by Kodiologist** [comment]
Looks good. In the documentation, can you link to Python's documentation for `argparse`? It should be doable with a `py:` cross-reference, although it always takes me some trial and error to find the syntax that Sphinx wants.

**Comment by refi64** [comment]
We should probably state how much is willing be be added. Having an
argument parsing is macro cool, but IMO there should be a definitive limit
as to how much extra stuff we want it to do / we're willing maintain
(whether it be "anything argparse does" or "just as-is") for the inevitable
point where someone opens and issue wanting to add a built-in nuclear
reactor as an option.

(Side note: is there much advantage here vs using the new annotation syntax
& plac? I guess that it's in stdlib could be reason enough.)

**Comment by Kodiologist** [comment]
Nobody is currently threatening to make this function do anything except delegate to `argparse`. I don't see where any creeping complexity would come in.

> the new annotation syntax & plac

I don't know what that is.

**Comment by brandonwillard** [comment]
Was there a discussion concerning why this is a good *core* language addition?

**Comment by Kodiologist** [comment]
[Not really.](https://github.com/hylang/hy/issues/1719#issuecomment-547469703) The thing is, our system of automatic imports is broken as designed. I'm currently thinking of just making the user import the functions or groups of functions they want, for the most part. The functions currently in `hy.core.language` will be split into themed modules, or just deleted.

**Comment by Kodiologist** [comment]
But at any rate, that sort of thing isn't in scope for this PR. `hy.core.language` will continue to be a grab back till that overhaul happens.

**Pull request merged**
