### PR TITLE
Tag macros

### LINKED ISSUE #1046: Add Clojure tagged literals or similar
Our reader macros have capabilities similar to Clojure's [tagged literals](http://clojure.org/reference/reader#_tagged_literals), but Hy's are limited to a single character after the dispatch character `#`. In Clojure, it can be an arbitrary symbol after the `#`. One-character macros make sense for something that gets used all the time, or for DSLs where something has to be repeated a lot. But for general user uses, it could be nicer to use a more descriptive name.

I'm not sure how hard it would be to adapt Hy's reader macros to read a symbol instead of a character.

### PR DESCRIPTION
**Pull request by gilch**
Closes #1046 

(See also #1230.)

This also changes the "sharp macro" term to "tag macro", to better match with Clojure. (And besides, the ASCII Number Sign `#` isn't the same as the Unicode `♯` Music Sharp Sign. This was misleading--They're similar but note that the horizontal lines of `#` wouldn't show up well on the musical staff.)

### CODE REVIEW

**Comment by Kodiologist** [comment]
> This was misleading

Do you also write the name of the programming language C# as "C♯"? :P

**Comment by gilch** [comment]
These history rewrites are trying my limited git skills. I think I can do this with an interactive rebase, but separating hunks from a single commit like that seems too hard. Maybe I can copy/paste and squash in a new commit. How would you approach this?

> Do you also write the name of the programming language C# as "C♯"?

[Officially, yes](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)#Name). But Unicode is hard to type, and everyone knows the substitution. Hy, on the other hand, actually does support Unicode symbols. Regardless, the stronger argument is really that "tag" is closer to what Clojure calls its version.

> is a bit vague; you mean something like "when `FORM` starts with an identifier character", right?

No, I meant what I said. Something like `#foo5` means the tag symbol is `foo5`, but `#foo 5` means the tag symbol is `foo` and the tagged form is `5`, which is an integer, not a symbol ("identifier"). If you think my proposed version is not clear, OK, let's work on it, but your proposed version is still not right either.

**Comment by Kodiologist** [comment]
> How would you approach this?

Rewind to the first commit (in an interactive rebase, with `git reset --hard`, or even with just `git checkout HEAD~`, although then you have to reconstruct the branch when you're done). Amend it to make the same substantive change to the documentation that you made in the second commit, but say "sharp macro" instead of "tag macro". Now reapply the second commit, resolving the merge conflict by just ignore the first commit's version. It should now be the case that renaming the feature is all that the second commit does.

It may actually be easiest, overall, if you put the name-change commit first. This will oblige you to change less stuff as you add tests and so on,  whether you make your changes by adding new commits or amending. (My own PRs often have some kind of cleanup in the first commit or commits and the change that the PR is really about in the later commits.)

> Something like `#foo5` means the tag symbol is `foo5`, but `#foo 5` means the tag symbol is foo and the tagged form is `5`, which is an integer, not a symbol ("identifier")

Actually, in Hy, `5` is an identifier at the lexical level; see e.g. `t_identifier` in `parsers.hy`. That's how we got #1143. But even in Python, `5` is a legal identifier character. It's just that, in Python as in other C-like languages, an identifier can't solely consist of digits.

**Comment by Kodiologist** [comment]
So to clarify, in Hy's case, I use the term "identifier" to describe a lexical entity, whereas a "symbol" is a Hy model object of type `HySymbol`.

**Comment by gilch** [comment]
> So to clarify, in Hy's case, I use the term "identifier" to describe a lexical entity

Ah, I see what you meant. I've also used that internal terminology in the first commit. But I don't think that is appropriate for the documentation, which is intended not just for Hy's developers, but for Hy's users, who can't be expected to be familiar with Hy's implementation details.

So, we could instead explicitly say that brackets `(`, `[`, `{`, quotes `'`, `"`, or white space (including `;` comments), will terminate a tag. Or we could just use more examples illustrating these.

**Comment by Kodiologist** [comment]
I don't think that inferring what "identifier character" means requires understanding the internal distinction between identifiers and symbols. You can write "symbol character" if you prefer. `5` is a symbol character, too. But listing out all the characters that aren't identifier characters is brittle.

Speaking of characters, I notice that you use the term "hashtag character" in the documentation. A hashtag is some sort of special token on Twitter that consists of a hash followed by an identifier. I think you mean "hash character".

**Comment by gilch** [comment]
> But listing out all the characters that aren't identifier characters is brittle.

Agreed, that's brittle. So are the examples, honestly, but at least we could potentially test those automatically. #1044. I'm inclined to remove the offending sentence altogether. This is documentation, not specification. The existing examples should suffice. Users can resolve this question pretty quickly in the repl.

> you use the term "hashtag character"

Heh, haven't you heard? That what all the kids are calling them nowadays. (And hashtags are used for a lot more than Twitter now.) "Pound", "hash", "number sign", "octothorp", and not to be confused with "sharp". This thing has too many names. Yeah, "hashtag" is arguably not correct for the character itself. I think we should just call it `#` in the docs and let the users worry about how to pronounce it.

**Comment by Kodiologist** [comment]
> I'm inclined to remove the offending sentence altogether.

Sounds fine to me.

> Heh, haven't you heard? That what all the kids are calling them nowadays.

But only because they aren't familiar with the terms "hash" or "tag" and so they think the word "hashtag" refers to the funny character rather than the whole construct. Right?

> I think we should just call it `#` in the docs and let the users worry about how to pronounce it.

That's fine, too. I did close #1274 for more or less the same reason.

**Comment by Kodiologist** [comment]
Good work!

Your test macro `#foo` should do something less trivial than returning its argument unaltered, so we test that the macro is actually run. (Optionally, make such a change to the other test macros in the file, too.)

It's also worth testing:
- Calling a single-character tag macro with whitespace after the tag
- Calling a multi-character tag macro with whitespace after the tag
- Defining and calling a macro whose name is subject to mangling
- Calling a tag macro (that's defined in the test file, not the built-in `#@`) on a non-literal expression

**Comment by gilch** [comment]
I just noticed that you can define the empty string as the name of a sharp macro on the current master (0.13.0), but there's no way to call it. This seems like a good time to fix that.

The ability to define sharp macros with a string name is currently necessary to define certain characters, like `#.`. With this update, arbitrary strings are allowed as tag names, but they can't be called if empty or if they contain whitespace (or a bracket or quote or semicolon). 

#1117 could probably fix this, since any string would have an associated symbol. For now, would it be better to disallow strings to define tags, or just empty strings?

**Comment by Kodiologist** [comment]
Keep allowing strings to define tags. You can disallow uncallable tag macros in this PR if you like, but I wouldn't require that to approve this.

**Comment by gilch** [comment]
OK, I think I got it working properly.

**Comment by Kodiologist** [comment]
Looking good. Don't forget about the case of mangling (bullet point 3 above).

**Comment by gilch** [comment]
Okay, I added a tests for mangling. I had to add a mangling call to the compiler to make it pass. I amended the first commit with that, since I figured that's where you'd want it. This would probably work better with #1117.

**Comment by Kodiologist** [comment]
Great. By the way, you can change the commit message for "Change sharp macros to tag macros" to say "rename" instead of "change" now that you've separated the functional changes out of it.

One other thing I noticed. On master, there's a pretty error message for using an unrecognized sharp macro:

    => #a 1
      File "<input>", line 1, column 1

      #a 1
      ^^
    HyTypeError: b"`a' is not a defined sharp macro."

Not so with your changes:

    => #a 1
    Traceback (most recent call last):
      File "/home/hippo/Desktop/hyenv/hy/hy/macros.py", line 220, in tag_macroexpand
        tag_macro = _hy_tag[None][tag]
    KeyError: 'a'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      [ ... ]
      File "/home/hippo/Desktop/hyenv/hy/hy/macros.py", line 224, in tag_macroexpand
        "`{0}' is not a defined tag macro.".format(tag)
    hy.errors.HyTypeError: <exception str() failed>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      [ ... ]
      File "/home/hippo/Desktop/hyenv/hy/hy/errors.py", line 46, in __str__
        line = self.expression.start_line
    AttributeError: 'HyString' object has no attribute 'start_line'

Could you look into this?

**Comment by gilch** [comment]
That should fix it. I needed to use `.replace()` on the mangled symbol to transfer the metadata.

**Comment by Kodiologist** [comment]
Thanks a lot. I'd be chuffed if you would review some of my open PRs as well (particularly ones that already have a review, so I can merge them).

**Pull request merged**
