### PR TITLE
Raise more appropriate error on missing keyword argument value

### PR DESCRIPTION
**Pull request by ewaldgrusk**

### CODE REVIEW

**Comment by kirbyfan64** [comment]
Why doesn't the message show the bad keyword argument anymore?

**Comment by ewaldgrusk** [comment]
Sorry, my mistake. I've updated the commit accordingly.

**Comment by berkerpeksag** [comment]
Thanks for the patch! :)

LGTM. It would be nice to add a simple test case.

**Comment by ewaldgrusk** [comment]
I assume you mean something like this:

~~~ hy
((fn [x] x) :x) ;; Make sure this raises a HyTypeError
~~~

If so, which file would be the best place for this test?

**Comment by berkerpeksag** [comment]
https://github.com/hylang/hy/blob/master/tests/compilers/test_ast.py looks like a good place to me. Thanks!

**Comment by ewaldgrusk** [comment]
Now I remember why my first attempt didn't show the bad keyword in the error message. I'm open to suggestions.

**Comment by paultag** [comment]
@ewaldgrusk Any chance we could get tests passing? I'd love to merge this!

**Comment by ewaldgrusk** [comment]
I have applied the fix suggested by @algernon (see #821 and #822) to the working directory of my local repository. The tests pass, but here’s the catch:

~~~ hy
;; Python 2.7.3 on Linux

((fn [💩] 💩) 1)
;; 1L

((fn [💩] 💩) :💩)
;; UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f4a9' …

((fn [💩] 💩) :💩 1)
;; UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f4a9' …
~~~

Needless to say that Python 3 is not affected by this.

**Comment by agentultra** [comment]
And when you have a mail client that renders those glyphs… I lol.

**Comment by Foxboron** [comment]
My terminal ain't even rendering those glyphs :/

**Comment by agentultra** [comment]
You read email in a terminal still? I have no sympathy. 😝

**Comment by Foxboron** [comment]
Atleast i got vim keybinds!

**Comment by algernon** [comment]
Merged this, after patching it up a bit with stuff from #822. All tests pass, and the error message is nice.

**Pull request closed without merging**
