### PR TITLE
Don't try to lex tag-macro calls as shebangs

### LINKED ISSUE #1334: Calling a tag macro whose name starts with `!` is lexed as a shebang line
=> (deftag !a [x] 1)
    <function <lambda> at 0x7fcdb322ab70>
    => (+ 1 #!a 1)
      File "<stdin>", line 1, column 6

      (+ 1 #!a 1)
           ^
    LexException: Ran into a HASHBANG where it wasn't expected.

My thinking is that shebang lines shouldn't be expected by the lexer; instead, they should be removed in preprocessing. The trick will be to make sure that line numbers are adjusted to compensate.

### PR DESCRIPTION
**Pull request by Kodiologist**
Fixes #1334.

### CODE REVIEW

**Comment by Kodiologist** [comment]
This is a 1337 pull request.

**Comment by kirbyfan64** [comment]
> This is a 1337 pull request.

Is it weird that I had to Google that..?

**Comment by Kodiologist** [comment]
No, it probably just means I'm old. ;_;

**Comment by gilch** [comment]
[Does anyone here speak L33T?](https://megatokyo.com/strip/9)

**Pull request merged**
