### PR TITLE
Fix `python_requires` in `setup.py`

### PR DESCRIPTION
**Pull request by Kodiologist**

### CODE REVIEW

**Review by allison-casey — COMMENTED** [review]
do we even need the upper bound? Most python libraries don't bother with it

**Comment by Kodiologist** [comment]
I think we should have it, yes, because I have yet to see a major release of Python that didn't break Hy. That is to say, I guarantee that 3.11 won't work until we make some changes to support it. The reason is that Hy is a lot more sensitive to Python internals than most Python libraries are.

Oddly, `<= 3.10.*` doesn't work either, so I went with `< 3.11`. Version specifiers seem to be hairy, especially since I couldn't find a library to let me quickly check a version against a specifier.

**Comment by allison-casey** [comment]
ahh didn't know there was a history of new python versions breaking hy.

**Review by allison-casey — APPROVED** [review]

**Comment by Kodiologist** [comment]
Yep. Hence I always construe support for a new major version of Python as a feature in NEWS.

**Pull request merged**
