### PR TITLE
Fix a typo in a tutorial example

### PR DESCRIPTION
**Pull request by krysros**

### CODE REVIEW

**Comment by Kodiologist** [comment]
Could you make the commit message a bit more descriptive? Say, "Fix a typo in a tutorial example"?

**Comment by Kodiologist** [comment]
It's the commit message that counts, not the PR title. Sorry, I know it's confusing.

**Comment by krysros** [comment]
I edited the typo directly on the GitHub page. I tried to change the commit message using `git commit --amend` and `git push --force` but without success. Sorry.

**Comment by Kodiologist** [comment]
Hmm, what happens if you try `git commit --amend -m 'Fix a typo in a tutorial example'` and then `git push --force`?

**Comment by krysros** [comment]
Thank you. Is it ok now?

**Comment by Kodiologist** [comment]
Yep, looks good.

**Pull request merged**
