### PR TITLE
Add array indexes cut tutorial

### PR DESCRIPTION
**Pull request by TristanCacqueray**
This change adds to the tutorial the hy way of indexing array.

### CODE REVIEW

**Comment by Kodiologist** [comment]
I think that by "array indexes", you mean "slices". Relatedly, `get` should be mentioned before `cut`. Otherwise, it seems to be implied that `foo[3]` would be written `(cut foo 3)` in Hy, rather than `(get foo 3)`.

**Comment by TristanCacqueray** [comment]
I meant slices indeed, and actually didn't knew about `cut` either as I am still discovering hy. It's a really awesome project btw, thanks :-)

**Comment by Kodiologist** [comment]
Okay, good, but I would avoid the word "array" because [it means something else in Python](https://docs.python.org/3/library/array.html). How about "collection" instead?

**Comment by TristanCacqueray** [comment]
Indeed. The new patch also added an assoc example.

**Comment by Kodiologist** [comment]
One step forward, one step back. I'd remove `assoc` or else show that it's equivalent to `(setv (get array 1) 42)`. Otherwise, the novice reader gets the impression that `get` is only a function and doesn't have the same flexibility as Python indices.

**Comment by TristanCacqueray** [comment]
Oh wow, I didn't realized you could set the value of a get expression like so :-)
Ok, let's keep this addition about get and cut since that is what i was looking for in the first place.

**Comment by Kodiologist** [comment]
Cool, looks good.

Writing documentation is hard; ideally, you want an encyclopedic knowledge of the part of the language you're documenting. Writing a tutorial is even more demanding because it needs to cover a lot of the language.

**Pull request merged**
