### PR TITLE
Release Hy 1.0a1

### PR DESCRIPTION
**Pull request by Kodiologist**
Typically I do a release every six months, but Hy has been moving so fast now (which I'm quite pleased about, I hasten to add—excellent work, folks) that I'd like to do an earlier release to help ease the pain of transition. Probably there will be another one around the middle of 2021.

I need two approvals from @hylang/core to do this. If I get them, I'll clean up NEWS and make the release.

### CODE REVIEW

**Comment by peaceamongworlds** [comment]
Given that we might be able to complete all of the `1.0` features in the normal release timeframe, would it not make sense to hold of a new release until then? I think that we started this discussion in #2008.

Or maybe we could have a release only with the new bug fixes (looking at the recent prs: #2028, #2024, #2020 etc) and not any of the breaking features (#1975 seems like a big one)? Then we could put of all the breaking features until `1.0`, so that users didn't have to re-write their code twice.

I don't really have a strong opinion about this though, so I'm willing to be convinced either way.

**Comment by Kodiologist** [comment]
> Given that we might be able to complete all of the 1.0 features in the normal release timeframe

I don't think that's realistically going to happen.

> Or maybe we could have a release only with the new bug fixes

I don't want to manage multiple lines of development before 1.0.

**Comment by Kodiologist** [comment]
@allison-casey @scauligi Can I get your input here?

**Comment by scauligi** [comment]
Considering the amount of major changes (and upcoming changes), I think it makes more sense to release as an alpha pre-release 1.0a1 instead of 0.21.

**Comment by Kodiologist** [comment]
Wouldn't that imply something near feature-completeness, or that we'll release 1.0 soon?

**Comment by allison-casey** [comment]
I dont think so, we can have as many alpha releases as we want. python3.9 had 6 alphas and 5 betas before release and we have much less to do than they do. I don't even think we even need to merge bugfixes on 0.20 just leave it as is for people to play around with something that is usable and stable.

**Comment by Kodiologist** [comment]
Okay, here's a full NEWS cleanup, and a new title for the PR. @allison-casey Do you anticipate any problems getting this new version to work with hy-interpreter?

**Comment by allison-casey** [comment]
shouldn't be an issue. just need to change the requirements file.

**Review by allison-casey — APPROVED** [review]

**Comment by allison-casey** [comment]
@scauligi @peaceamongworlds is there any reason not to approve this at this point? we need two approvals for releases.

**Review by scauligi — APPROVED** [review]

**Comment by Kodiologist** [comment]
Thanks. I'll merge this and release it tomorrow or Monday.

**Pull request merged**
