### PR TITLE
Remove redundant assignments with nested ifs (closes #842)

### LINKED ISSUE #842: Conditionals waste assignments.
Conditionals containing statements are doing unnecessary work. I know, Python is not renowned for its performance, but let's not make it worse. This kind of thing can matter inside nested loops.

Currently a `cond` like this:

```
(cond [0 "zero"]
      [1 "one"]
      [True (assert 0)])
```

Turns into this:

```
if 0:
    _hy_anon_var_3 = 'zero'
else:
    if 1:
        _hy_anon_var_2 = 'one'
    else:
        if True:
            assert 0
            _hy_anon_var_1 = None
        else:
            _hy_anon_var_1 = None
        _hy_anon_var_2 = _hy_anon_var_1
    _hy_anon_var_3 = _hy_anon_var_2
```

But wouldn't it would work just as well like this?

```
if 0:
    _hy_anon_var_1 = 'zero'
elif 1:
    _hy_anon_var_1 = 'one'
elif True:
    assert 0
    _hy_anon_var_1 = None
```

Half the assignments for the same effect. And the `hy --spy` output is much more readable. I don't think CPython can automatically optimize this kind of thing. I know not all of them happen for any given branch, but the deeper ones will still do more assignments than they should.

Python has no switch/case. Sometimes you can get away with dictionary lookups instead, but if you need side effects or performance, you're supposed to use cascading `elif` where you would have used a switch. 

Currently there's no `elif` form in Hy. `cond` is the closest we've got. Now I could write nested `if`s instead (or a macro to do it for me) but look at what it turns into:

```
=> (if 0 "zero"
... (if 1 "one"
...       (assert 0)))
if 0:
    _hy_anon_var_2 = 'zero'
else:
    if 1:
        _hy_anon_var_1 = 'one'
    else:
        assert 0
        _hy_anon_var_1 = None
    _hy_anon_var_2 = _hy_anon_var_1
```

Not quite as bad as the `cond` since we have a final `else`, but still twice what is necessary:

```
if 0:
    _hy_anon_var_1 = 'zero'
elif 1:
    _hy_anon_var_1 = 'one'
else:
    assert 0
    _hy_anon_var_1 = None
```

Maybe it's too hard to optimize nested `if` forms like that? Is `cond` defined in terms of Hy's `if` form in the first place? I didn't implement `cond` but you could totally do it as a macro in terms of `if`.

Why not extend Hy's `if` to work like Arc Lisp's (as I proposed in #830 ), which can accept two or more arguments:

```
=> (if a b)
if a:
    _hy_anon_var_1 = b
else:
    _hy_anon_var_1 = None
=> (if a b
         c)
if a:
    _hy_anon_var_1 = b
else:
    _hy_anon_var_1 = c
=> (if a b
       c d)
if a:
    _hy_anon_var_1 = b
elif c:
    _hy_anon_var_1 = d
else:
    _hy_anon_var_1 = None
=> (if a b
       c d
         e)
if a:
    _hy_anon_var_1 = b
elif c:
    _hy_anon_var_1 = d
else:
    _hy_anon_var_1 = e
```

etc., for any number of inner `elif`s you need.
- Now you only have to generate AST for the new `if` form, instead of optimizing nested forms. 
- It make Hy's `if` act more like Python's cascading `elif`.
- This doesn't break existing Hy code, since we're not using more than 3 arguments now, and the 2 and 3 argument cases work exactly like before. 
- `cond` can be redefined in the same way, and get the same benefits.

### PR DESCRIPTION
**Pull request by kirbyfan64**
This just reuses the same temporary across nested if branches.

### CODE REVIEW

**Comment by kirbyfan64** [comment]
Bump? I would've thought @gilch would like this.

**Comment by farhaven** [comment]
LGTM, :+1:

**Comment by gilch** [comment]
>  I would've thought @gilch would like this.

:+1: 

I might have said so sooner if you had an example of what it changed, but it took a while to figure out what you were talking about. As it was it had to wait until I had the free time to test it.

Something like this...

Before:
```Hy
=> (if 1 1 (if 2 (setv x 2) (if 3 3)))
if 1:
    _hy_anon_var_2 = 1
else:
    if 2:
        x = 2
        _hy_anon_var_1 = x
    else:
        _hy_anon_var_1 = (3 if 3 else None)
    _hy_anon_var_2 = _hy_anon_var_1
```
After:
```Hy
=> (if 1 1 (if 2 (setv x 2) (if 3 3)))
if 1:
    _hy_anon_var_1 = 1
elif 2:
    x = 2
    _hy_anon_var_1 = x
else:
    _hy_anon_var_1 = (3 if 3 else None)
```
I should probably just set up another virtual environment so I can compare a new branch side by side with the current version.

**Comment by gilch** [comment]
Also, put the reference #842 in the comment not just the title, so we can click the link instead of copy-pasting. It makes it easier to follow.

I also noticed that this improves `cond` because it's implemented in terms of `if`.

One other thing I think mentioned in #842, in Common Lisp, `cond` has an `else` part too, so
```Lisp
* (cond (nil 0) (1))

1
```
is the same as
```Lisp
* (cond (nil 0) (t 1))

1
```
but without a wasted check at the end. Hy should support this to, so
```Hy
=> (cond [nil 0] [1])
(0 if None else 1)
```
should work, instead of the nearest approximation we have now:
```Hy
=> (cond [nil 0] [True 1])
(0 if None else (1 if True else None))
```
Which has the wasted `if True`. Since this closes #842, now would be a good time to fix it. Or I can open it as new separate issue if you prefer.

**Comment by algernon** [comment]
I'd suggest a new issue for the else branch of cond. Shouldn't be too hard to implement after this, I hope!

**Comment by algernon** [comment]
Looks good to me, by the way, so :+1:

**Comment by kirbyfan64** [comment]
Rebased and ready to merge!

**Comment by kirbyfan64** [comment]
Uhhh...I have no clue what those test failures are. They have nothing to do with this PR!?

Anyway, I already have what @gilch just described in working form, so I can commit it if you want. :)

**Comment by zackmdavis** [comment]
@kirbyfan64 

> Uhhh...I have no clue what those test failures are. They have nothing to do with this PR!?

A [new version of Coverage](http://coverage.readthedocs.org/en/latest/changes.html#version-4-0-20-september-2015) got released yesterday; we probably need to update our Travis configuration.

**Comment by algernon** [comment]
@kirbyfan64 if you already have it, feel free to push it here, no need for a separate PR then.

**Comment by kirbyfan64** [comment]
Well, it *should* work, but now some completely unrelated *mathematics* test is failing? Because that makes perfect sense...

**Comment by kirbyfan64** [comment]
...more freaking test failures. Turns out, eliminating `if True` and `if False` branches is surprisingly difficult...

**Comment by kirbyfan64** [comment]
Ok; now all the tests pass!! :D

**Comment by gilch** [comment]
Can we merge this yet? Travis says the build failed, but I think that was a different issue. Is there some way to force a retest?

**Comment by gilch** [comment]
I'd merge it myself, but the failed check is making me uncomfortable. The false positive could be masking a real positive.

**Comment by zackmdavis** [comment]
@gilch [This StackOverflow answer](http://stackoverflow.com/a/17624403) claims that the crude measure of closing and re-opening the pull-request will force a rebuild. Let's try it.

**Pull request merged**
