### PR TITLE
Make `defmain` args optional or variadic when empty

### PR DESCRIPTION
**Pull request by brandonwillard**
Closes hylang/hy#1707.

### CODE REVIEW

**Comment by Kodiologist** [comment]
Why add the `&optional`s by force? The programmer can add it if they want it.

**Comment by brandonwillard** [comment]
That just avoids cryptic error messages.  We can remove it, though.

**Comment by Kodiologist** [comment]
How about improving the error messages?

**Comment by brandonwillard** [comment]
There are none, so we're actually talking about adding some.  Even so, the cryptic results have more to do with the likely unexpected default first `sys.argv` value and the error messages caused by it.  

Furthermore, a user specifying their own arguments, e.g. `(defmain [a b] (print a))`, might not expect the first argument to always be the executable/script name instead of the first cmdline argument.  Perhaps it would be better to make that value accessible in some other way and let the user-specified arguments correspond directly to the cmdline arguments.  
At the very least, the docs string should state that the first macro argument will always be the binary/script name.

**Comment by Kodiologist** [comment]
> There are none, so we're actually talking about adding some.

There are no custom error messages for `defmain`, but if you define `(defmain [x y] …)` and call the program without arguments, you get `TypeError: <lambda>() missing 1 required positional argument: 'y'`, which is an example of the cryptic error messages you were referring to, right?

Regarding your second paragraph, yeah, it's surprising that the first argument is the executable name, and indeed that's part of why it's surprising that `(defmain [] …)` doesn't work. The documentation should be clearer about this, and perhaps we should change it.

**Comment by brandonwillard** [comment]
Will do.

No, didn't work when I first tried.

**Pull request merged**
