### PR TITLE
Python 3.8 development has started 😉

### PR DESCRIPTION
**Pull request by vodik**
https://docs.python.org/3.8/whatsnew/3.8.html

Lets keep an eye on its compatibility.

### CODE REVIEW

**Comment by vodik** [comment]
Ah, it was pulled because of OpenSSL issues: https://github.com/travis-ci/travis-ci/issues/9069

**Comment by Kodiologist** [comment]
Seeing as it doesn't work, we can close this, yes?

**Comment by vodik** [comment]
Yeah, let's move it to an issue.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Kodiologist** [comment]
Even an issue seems premature. Python 2.7 isn't even out yet.

**Pull request closed without merging**
