### PR TITLE
Add Travis badge to README

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by Kodiologist** [comment]
This probably won't work reliably. See https://github.com/hylang/hy/pull/1688#issuecomment-431617074 .

**Comment by gliptak** [comment]
@Kodiologist hmm ... this is the setup most Github/Travis projects use pointing to last build of master (and yes there still might be failures with releases of Python and unpinned dependencies)

**Comment by Kodiologist** [comment]
Yes, and consequently they have to take [this bug](https://github.com/hylang/hy/pull/1688#issuecomment-431617969) on the chin, if I understand correctly.

**Comment by refi64** [comment]
Reminds me, I have almost-working GitHub Actions support that I need to
finish up.

**Pull request closed without merging**
