### PR TITLE
Update copyright years

### PR DESCRIPTION
**Pull request by Kodiologist**

### CODE REVIEW

**Comment by refi64** [comment]
Do we [actually want to do this](https://stackoverflow.com/a/2391555/2097780)?

**Comment by Kodiologist** [comment]
We are indeed revising the code every year, so mentioning the new year seems appropriate. If you want to include earlier years, particularly 2012, the year the first commit of Hy was made, we can do that.

**Comment by Kodiologist** [comment]
@refi64 Do you want to?

**Comment by Kodiologist** [comment]
I guess not.

**Comment by refi64** [comment]
Oof sorry, I starred this in my email to take a look later and then
completely forgot. Yeah, it's not a huge deal.

**Pull request merged**
