### PR TITLE
Fixes 'J' being parsed as a complex and fixes error messages for bad `defmacro` names

### PR DESCRIPTION
**Pull request by scauligi**
Two relatively minor bugfixes, with regression tests. No associated open issues (that I'm aware of).
Let me know if I should split this into two commits / two PRs.

### CODE REVIEW

**Comment by Kodiologist** [comment]
I think one PR is okay, but split it into two commits. Also, use `pytest.raises` for the exception tests, and add items to NEWS.

**Comment by scauligi** [comment]
Done!

**Review by Kodiologist — APPROVED** [review]

**Comment by Kodiologist** [comment]
@allison-casey Does your thumbs-up on the above comment mean that you reviewed the PR and approve of it?

**Comment by allison-casey** [comment]
I did and I do. Actually ran into the macro-name error yesterday so glad to see this one come through.

**Comment by Kodiologist** [comment]
Oh nice, this is the first time in forever we can merge a PR because we have more than one approval.

**Pull request merged**
