### PR TITLE
Add exclusive or logical operator

### PR DESCRIPTION
**Pull request by tuturto**
Added xor to complement and, or, not operators. Standard python
falsey/truthy semantics are followed. This implementation works for
two or more parameters.

### CODE REVIEW

**Comment by paultag** [comment]
Neat! Nice work!

Can we make this into a real function? Any reason it has to be a macro?

**Comment by gilch** [comment]
[More than two parameters](https://en.wikipedia.org/wiki/XOR_gate#More_than_two_inputs) is confusing if you call it `xor`. Note that `(xor a b c)` is not `(xor (xor a b) c)` in general. But this does hold for `+` etc. It should be called `one-hot` or `parity`, depending on which interpretation you're using, or else limited to two arguments.

**Comment by tuturto** [comment]
@paultag it used to have different implementation in case of two parameter input, but not anymore. I'll change it to function. Then @kirbyfan64's good point about macroerror gets solver too.

@gilch hm.. I wasn't aware that there's different views how this should work. Probably best to switch it to work with two parameters only and avoid possible misunderstandings.

**Comment by gilch** [comment]
A possible Python implementation:
```Python
xor = lambda a, b: bool(a) ^ bool(b)
```

**Comment by algernon** [comment]
Looks good to me, :+1:

**Comment by paultag** [comment]
Nice! Thanks a ton! :D

**Pull request merged**
