### PR TITLE
Test PyPy3 on Travis

### LINKED ISSUE #614: pypy3
Just released. Let's get tests passing.

### PR DESCRIPTION
**Pull request by Kodiologist**
Closes #614.

### CODE REVIEW

**Comment by gilch** [comment]
Shouldn't we add this to tox too? Is Travis actually running flake8 and coverage? I can't find the output. I'm not sure how our testing works since we stopped using nose, because #1289.

**Comment by Kodiologist** [comment]
> Shouldn't we add this to tox too?

Good point. Done.

> Is Travis actually running flake8 and coverage?

Currently, no.

**Comment by Kodiologist** [comment]
[And it looks like the last commit that Coveralls detected was in 2014.](https://coveralls.io/github/hylang/hy)

**Comment by gilch** [comment]
Conflict. Drop Python 3.3, due to #1401

**Comment by Kodiologist** [comment]
Aye-aye, rebased.

**Pull request merged**
