### PR TITLE
Give an error when &kwonly is used in a macro definition

### LINKED ISSUE #959: &kwonly in defmacro
```
=> (defmacro foo [&kwonly b] `(print ~b))
import hy
from hy import HyExpression, HySymbol

@hy.macros.macro('foo')
def _hy_anon_fn_1(*, b):
    return HyExpression((([] + [HySymbol('print')]) + [b]))
=> (foo)
  File "<input>", line 1, column 1

  (foo)
  ^---^
HyMacroExpansionError: expanding `foo': TypeError("_hy_anon_fn_1() missing 1 req
uired keyword-only argument: 'b'",)

=> (foo :b 42)
  File "<input>", line 1, column 1

  (foo :b 42)
  ^---------^
HyMacroExpansionError: expanding `foo': TypeError('_hy_anon_fn_1() takes 0 posit
ional arguments but 2 were given',)

=> (foo ':b 42)
  File "<input>", line 1, column 1

  (foo ':b 42)
  ^----------^
HyMacroExpansionError: expanding `foo': TypeError('_hy_anon_fn_1() takes 0 posit
ional arguments but 2 were given',)

=> (macroexpand '(foo :b 42))
from hy.core.language import macroexpand
from hy import HyExpression, HyInteger, HyKeyword, HySymbol
macroexpand(HyExpression(((([] + [HySymbol('foo')]) + [HyKeyword('\ufdd0:b')]) +
 [HyInteger(42)])))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\ME\Code\repos\hy/hy/core/language.hy", line 265, in macroexpand

    (hy.macros.macroexpand form name))
  File "C:\Python34\Scripts\env-hy\lib\site-packages\hy\macros.py", line 155, in
 macroexpand
    tree = macroexpand_1(tree, module_name)
  File "C:\Python34\Scripts\env-hy\lib\site-packages\hy\macros.py", line 194, in
 macroexpand_1
    raise HyMacroExpansionError(tree, msg)
hy.errors.HyMacroExpansionError: <unprintable HyMacroExpansionError object>
```
The keywords appear to work as simple positional arguments. If there's no way to provide a `&kwonly` argument to a macro form, then it should not be allowed in `defmacro`.

Either change the macro system to accept keyword arguments, or signal an error when someone attempts to use `&kwonly` etc. in `defmacro`.

### PR DESCRIPTION
**Pull request by kirbyfan64**
(closes #959)

### CODE REVIEW

**Comment by kirbyfan64** [comment]
BTW, is there a way to test this? I looked in the tests, but it seems there are no tests for anything like this...

**Comment by gilch** [comment]
I wonder if we should reconsider the all the other `&` parameters. Clearly we need `&rest`. I'm not sure about how `&key` works, because it's not documented. What about `&optional`? It should work positionally, but we can't skip over an optional arg with a keyword.

**Comment by gilch** [comment]
I think you could put an invalid macro declaration in a try form and catch the HyTypeError. Something like this:
```Python
try:
    <test code>
    raise Error("HyTypeError expected")
except HyTypeError:
    pass
```
The testing framework might even have a decorator for this kind of thing. I'd have to look at the docs.

**Comment by gilch** [comment]
I checked, and nose does have a [decorator](https://nose.readthedocs.org/en/latest/testing_tools.html) for this: `nose.tools.raises`. We don't seem to be using `nose.tools` in any tests, but I did see the `try` pattern I mentioned above. This should also work as a native Hy test.

**Comment by kirbyfan64** [comment]
@gilch Test added.

**Comment by tuturto** [comment]
```&key```, ```&optional``` and ```&kwargs``` probably don't make sense in the context of macros currently.

The code looks solid to me :+1:

**Comment by gilch** [comment]
@kirbyfan64, can you add checks and tests for ```&key```, ```&optional``` and ```&kwargs```?

**Comment by kirbyfan64** [comment]
@gilch But `&optional` and `&key` work as expected with macros:

```
ryan@DevPC-LX:~$ hy
hy 0.11.0 using CPython(default) 2.7.6 on Linux
=> (defmacro x [&optional v] (if v `"v was given" `"v was not given"))
^[[
ryan@DevPC-LX:~$ hy
hy 0.11.0 using CPython(default) 2.7.6 on Linux
=> (defmacro x [&optional v] (if v `"v was given" `"v was not given"))
=> (x 1)
u'v was given'
=> (x)
u'v was not given'
=> (defmacro y [&key {"v" nil}] (if v `"v was given" `"v was not given"))
=> (y 1)
u'v was given'
=> (y)
u'v was not given'
=> 
ryan@DevPC-LX:~$ 
```

**Comment by kirbyfan64** [comment]
@gilch But I did add `&kwargs`.

Tell me when to squash the commits!

**Comment by gilch** [comment]
This test won't fail if `defmacro` starts accepting `&kwonly` again. Read it carefully. It only asserts that *if* there's a `HyTypeError`, that it has the stated message. If there's not an error it doesn't complain.
```Hy
(try
    (eval '(defmacro f [&kwonly a b]))
    (except [e HyTypeError]
      (assert (= e.message "macros cannot use &kwonly"))))
```
You need to detect the case where no exception happens, something like this:
```Hy
(try
    (do 
      (eval '(defmacro f [&kwonly a b]))
      (raise (Exception "HyTypeError expected for &kwonly in defmacro")))
    (except [e HyTypeError]
      (assert (= e.message "macros cannot use &kwonly"))))
```

**Comment by kirbyfan64** [comment]
@gilch Fixed. I also squashed the commits.

**Comment by gilch** [comment]
We've got merge conflicts now, can you fix those?

There's a good enough case for keeping `&optional`, I think. I'm still not sure about `&key` though. The only documentation on `&key` says
> The difference here is that since it’s a dictionary, you can’t rely on any specific ordering to the arguments.

Yet we *must* rely on ordering of the arguments in a macro because we *can't* supply them using keywords.

**Comment by kirbyfan64** [comment]
@gilch Fixed.

**Comment by paultag** [comment]
LGTM; RFR @hylang/core

**Comment by gilch** [comment]
What possible use is `&key` in a Hy macro? That still doesn't appear to be disallowed by this PR. Show me a good use case and I'll merge it now, otherwise, can you give an error for `&key` too?

**Pull request merged**
