### PR TITLE
delmacro and macro redefinition warning

### LINKED ISSUE #1689: Macro name shadowing/collisions and removal
A user defined `require` macro will block the compilation of all `require` statements and there's little recourse for undoing this.  As far as I can tell, a user would have to remove the macro entry in `hy.macros._hy_macros` (or `__macros__` under #1682) and, since the macro dictionary is a Hy internal, that isn't a very reasonable recommendation.

Nearly the same situation occurs with plain functions:
```clojure
hy 0.15.0+39.gd2319dc using CPython(default) 3.6.6 on Linux
=> (defn test [] (print "test function"))
=> (defmacro test [] (print "test macro"))
<function <lambda> at 0x7fc95f8c0ea0>
=> (test)
test macro
```
Since we can't simply `(del test)` (the macro or the plain function) or redefine the function in order to regain it, this situation can easily lead to confusion and frustration.
(I imagine this might have an issue of its own already, but I didn't see one in my first pass.)
One can reset the Hy/Python session, but, when that's the easiest/best option, something needs to be fixed!

This general discord between macros, plain functions and Hy special forms like `require` is not a trivial issue, and, while we could make it easier to work around the aforementioned situations (e.g. have the compiler apply `del` to macros and tags), we should simply rethink and/or formalize the interaction between these three.

For instance, I believe I've mentioned/asked this before, but if the functions backing macros used their macro's names and were defined directly in their namespaces, then this wouldn't be an issue.

Anyway, thoughts?

### PR DESCRIPTION
**Pull request by allison-casey**
closes #1689 

adds a `RuntimeWarning` when a user attempts to redefine a core macro and a new core macro `delmacro` a macro equivalent of `del` that deletes macros in the calling namespace. 

So the case of redefining `require` would look like:
```clojure
=> (require tests.resources.tlib [qplah])
hy.macros.require('tests.resources.tlib', None, assignments=[['qplah', 'qplah']], prefix='')
None
=> (defmacro require [] 1)
<string>:1: RuntimeWarning: require already refers to: `require` in module: `builtins`, being replaced by: `__console__.require`
  (defmacro require [] 1)
hy.macros.macro('require')(lambda hyx_XampersandXcompiler: 1)
None
=> (require)
1
1
=> (delmacro require)
None
=> (require tests.resources.tlib [parald])
hy.macros.require('tests.resources.tlib', None, assignments=[['parald', 'parald']], prefix='')
None
```

### CODE REVIEW

**Comment by allison-casey** [comment]
oh looks like a fun situation, where using `eval-and-compile` makes tests pass, but breaks the repl and `eval-when-compile` makes repl work but breaks tests lol. will fix

**Comment by allison-casey** [comment]
so pretty sure this is an issue related to #2150 where different hy files can be evaluated a different number of times. so we might be attempting to delete a macro that was already deleted previously in the case of `eval-and-compile` or not deleting a macro that was defined more than once in the case of `eval-when-compile`. Easy solution would be to not `NameError` on a `delmacro` call that doesn't exist, but that would make `delmacro `act differently than python `del`. I have no problem with that personally. we can always start `NameError`ing later if we fix #2150. What do y'all think?

**Comment by Kodiologist** [comment]
As a general rule, I think it's fine for code that's supposed to delete something to silently do nothing if the thing doesn't exist. When it raises an error, that usually just makes programmers need to catch and ignore it. The inconsistency with `del` isn't too important considering how complex the question of whether a macro exists is.

**Comment by allison-casey** [comment]
For what it's worth i don't think clojure attempts to solve the whole problem. Just warn and assume the user knows what their doing. Better macro introspection would definitely help and should probably be on the post 1.0 roadmap for sure

Fair enough. I'll change that

**Comment by Kodiologist** [comment]
But `record` is still there. I mean that you don't need to bind the context manager to a name at all, because you won't use it.

**Comment by allison-casey** [comment]
woops my b, missed that

**Comment by Kodiologist** [comment]
Ah, shoot, I didn't rebase because I assumed you already had. My mistake.

**Pull request merged**
