### PR TITLE
Correct documentation of earmuff behavior

### LINKED ISSUE #1714: Remove outdated reference to earmuffs in docs
For the interop example in the [docs](https://github.com/hylang/hy/blob/55ec6a055256a44ac3e16bb4cbb8aa9cfb8c6f44/docs/language/interop.rst),
```clj
(setv *this-will-be-in-caps-and-underscores* "See?")
(defn greet [name] (print "hello from hy," name))
```
and ignoring the namespace import problem, the translation to Python
```python
import hy
import greetings

greetings.greet("Foo") # prints "Hello from hy, Foo"
print(THIS_WILL_BE_IN_CAPS_AND_UNDERSCORES) # prints "See?"
```
of the constant doesn't work:
```
In [1]: import hy

In [2]: from greetings import *

In [3]: whos
Variable                                                       Type        Data/Info
------------------------------------------------------------------------------------
greet                                                          function    <function greet at 0x7fb360bdef28>
hy                                                             module      <module 'hy' from '/usr/l<...>packages/hy/__init__.py'>
hyx_XasteriskXthis_will_be_in_caps_and_underscoresXasteriskX   str         See?
name                                                           function    <function name at 0x7fb3600b98c8>
```
A quick test shows this is due to earmuffs:
```clj
(setv var1 "apple")
(setv *var2* "banana")
(setv var-3 "pear")
(setv *var-4* "peach")
```
```
In [1]: import hy

In [2]: from greetings import *

In [3]: whos
Variable                        Type      Data/Info
---------------------------------------------------
hy                              module    <module 'hy' from '/usr/l<...>packages/hy/__init__.py'>
hyx_XasteriskXvar2XasteriskX    str       banana
hyx_XasteriskXvar_4XasteriskX   str       peach
var1                            str       apple
var_3                           str       pear
```
This is with hy 0.15.0+60.g55ec6a05. It looks like https://github.com/hylang/hy/pull/1517 removed it, so the docs should be updated.

### PR DESCRIPTION
**Pull request by edouardklein**
Another piece of fix #1714

### CODE REVIEW

**Comment by Kodiologist** [comment]
Good catch. I'd say it's probably best not to get into mangling here, so we can just write "(e.g. dashes turn to underscores)".

**Comment by Kodiologist** [comment]
So, do you want to change it per my comment?

**Comment by edouardklein** [comment]
Yep, I'm just away from the office, I only have a cell phone. If that's
allright I'll do it next week.

I'll try sometime in the next few days, but I can't promise I'll be
confortable enough with github's web tools on mobile to be successful.

Le sam. 2 févr. 2019 à 15:17, Kodi Arfer <notifications@github.com> a
écrit :

**Comment by Kodiologist** [comment]
I can just rebase it for you if you agree to the change.

**Comment by edouardklein** [comment]
Of course! It was just a small catch after I updated hy and my earmuffs did
not interop with Python anymore. I searched the docs and saw that it should
still work, and then came to the issues and saw the discussion about
mangling. Please do what is the easiest for you, or instruct me to do what
is easiest for everyone and I'll be happy to do it next week.

Le dim. 3 févr. 2019 à 02:04, Kodi Arfer <notifications@github.com> a
écrit :

**Comment by Kodiologist** [comment]
All done, thanks.

**Pull request merged**
