### PR TITLE
Refactor/compiler cleanup

### PR DESCRIPTION
**Pull request by allison-casey**
closes #1399 This doesn't cover everything, (namely I think that there needs to be another pass against the core logic), but I'd rather get all the quality of life improvements in this than do all the bikeshedding around that kind of deep refactor right now.

### CODE REVIEW

**Comment by Kodiologist** [comment]
Overall, I'm not a fan. These changes add needless temporary variables, move parentheses to hang out on their own line when grouping is already made clear by indentation, and change comments to string literals in contexts where docstrings aren't actually allowed. Removing unused imports is useful, and I'll take your word for it that the type annotations will become useful, but the rest we're better off without.

**Comment by Kodiologist** [comment]
I forgot to mention: I think that adding detailed documentation for internal methods and helper functions of a class that's not supposed to be user-visible is a mistake. We don't want to maintain that.

**Comment by allison-casey** [comment]
Pulling this, we can argue about syntax after 1.0

**Comment by Kodiologist** [comment]
Fair enough.

**Pull request closed without merging**
