### PR TITLE
Tutorial in Python3

### PR DESCRIPTION
**Pull request by freezas**
After discussions in #1385 and #1272 I decided to change all the examples to Python3.

### CODE REVIEW

**Comment by Kodiologist** [comment]
Looking good, thanks. There's still at least one `raw-input` in Hy code hanging around, so don't forget that. Also, you don't need a separate commit for each change when the changes are this small and to the same purpose. You can meld all your commits together with `git rebase -i master`.

**Comment by freezas** [comment]
D'oh! I've replaced the `raw-input` in the Hy examples as well now.

I tried to rebase it, but it looks like the forked branch is still made of multiple commits... Or is this okay now?
I actually wanted to work on a seperate branch and merge it back to the fork's master, but I forgot to do that correctly. Would that be better next time?

**Comment by Kodiologist** [comment]
Ah, yes, I missed the fact that you worked on `master` instead of using a feature branch. You should indeed use a feature branch in the future.

**Comment by Kodiologist** [comment]
> `(1L 2L 3L)`

There shouldn't be trailing `L`s when you're running Hy on Python 3. Are you sure this is correct? It's worth running through the code and making sure it all works and produces the right output, if you haven't already.

**Comment by Kodiologist** [comment]
It would also be wise to say something like "This tutorial assumes you're running Hy under Python 3; things are a bit different under Python 2" near the top.

**Comment by freezas** [comment]
I've removed the trailing L's and added a remark about using Python 3.

I've ran most of the examples. Some of the examples don't work. The things I think need to be fixed are:

* an install of Django and import of 'models' in order to run the examples about class variables
* a 'require' in order to use the 'loop' expression in the example of Protips!

I wasn't sure if you want these in the same pull request. Should I try to fix those examples anyway?

There are also more issues I wanted to discuss first before changing more of the tutorial, but maybe it's better to discuss that on the mailing list. Or is there already a plan to work on improving the tutorial?

**Comment by Kodiologist** [comment]
> I wasn't sure if you want these in the same pull request. Should I try to fix those examples anyway?

It's your choice. When you're ready, add yourself to AUTHORS in a new commit and I'll merge.

> There are also more issues I wanted to discuss first before changing more of the tutorial, but maybe it's better to discuss that on the mailing list.

Whichever you like, although I think issues and PRs are read more widely than the mailing list. I rarely look at the mailing list.

> Or is there already a plan to work on improving the tutorial?

Nope, no plans right now.

**Comment by freezas** [comment]
I've add my name to the AUTHORS file.

I'll take another look at Hy and the tutorial another time again.

**Comment by Kodiologist** [comment]
Sorry, when I said "a new commit", I meant a separate one. See CONTRIBUTING.rst.

**Comment by Kodiologist** [comment]
I'll do it.

**Comment by Kodiologist** [comment]
I couldn't push ("permission denied"; perhaps you unchecked "Allow edits from maintainers"), so I merged it manually.

**Comment by freezas** [comment]
Thanks!

**Pull request closed without merging**
