### PR TITLE
Add hy.interact

### LINKED ISSUE #1323: Make repl embeddable
Look what IPython can do:
```Python
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> foo = 42
>>> import IPython; IPython.embed()
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: foo
Out[1]: 42

In [2]: bar = True

In [3]: exit

>>> foo
42
>>> bar
True
>>>
```
Let's try that in Hy.
```Python
(hy36env) C:\Users\ME\workspace\hy36env\Scripts>python
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> foo = 42
>>> from hy.cmdline import run_repl
>>> run_repl()
hy 0.13.0+15.g2e465db using CPython(v3.6.1:69c0db5) 3.6.1 on Windows
=> foo
Traceback (most recent call last):
  File "c:\users\me\documents\github\hy\hy\importer.py", line 198, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'foo' is not defined
=> (exit)

(hy36env) C:\Users\ME\workspace\hy36env\Scripts>
```
We can launch the repl from Python. However, we lost our vars, and `(exit)` kicks us all the way back to the system shell. Could Hy's repl be made embeddable like IPython?

### PR DESCRIPTION
**Pull request by vodik**
Closes #1323

Really trivial to implement as we already properly subclass `code.InteractiveConsole`. Matches `code.interact` API.

### CODE REVIEW

**Comment by Kodiologist** [comment]
How about a test?

**Comment by gilch** [comment]
@vodik I also want NEWS and docs for this. It can be a separate PR if that's easier.

**Comment by gilch** [comment]
@Kodiologist It's a single function for user interaction. How would you want this tested?

**Comment by Kodiologist** [comment]
Pass in `(+ 1 1)` and check that you get `2` back. It shouldn't be hard if you temporarily redirect standard input and output.

**Comment by Kodiologist** [comment]
I'm closing this because of the lack of follow-up. Please reopen if you want to pick this up again.

**Pull request closed without merging**
