### PR TITLE
Improve error messages related to _storeize

### PR DESCRIPTION
**Pull request by kirbyfan64**
`x.hy`:

```hy
(setv [1 2] 1)
```

Before:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "hy/cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "hy/cmdline.py", line 335, in cmdline_handler
    return run_file(options.args[0])
  File "hy/cmdline.py", line 210, in run_file
    import_file_to_module("__main__", filename)
  File "hy/importer.py", line 76, in import_file_to_module
    _ast = import_file_to_ast(fpath, module_name)
  File "hy/importer.py", line 68, in import_file_to_ast
    return hy_compile(import_file_to_hst(fpath), module_name)
  File "hy/compiler.py", line 2581, in hy_compile
    result = compiler.compile(tree)
  File "hy/compiler.py", line 433, in compile
    ret = self.compile_atom(_type, tree)
  File "hy/compiler.py", line 425, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "hy/compiler.py", line 624, in compile_raw_list
    ret = self._compile_branch(entries)
  File "hy/compiler.py", line 489, in _compile_branch
    return _branch(self.compile(expr) for expr in exprs)
  File "hy/compiler.py", line 316, in _branch
    results = list(results)
  File "hy/compiler.py", line 489, in <genexpr>
    return _branch(self.compile(expr) for expr in exprs)
  File "hy/compiler.py", line 445, in compile
    raise_empty(HyCompileError, e, sys.exc_info()[2])
  File "hy/_compat.py", line 66, in raise_empty
    raise t(*args)
hy.errors.HyCompileError: Internal Compiler Bug 😱
⤷ TypeError: Can't assign / delete a <class '_ast.Num'> object
Compilation traceback:
File "hy/compiler.py", line 433, in compile
    ret = self.compile_atom(_type, tree)
  File "hy/compiler.py", line 425, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "hy/compiler.py", line 2001, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "hy/compiler.py", line 425, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "hy/compiler.py", line 2062, in compile_def_expression
    expression.start_column)
  File "hy/compiler.py", line 2102, in _compile_assign
    st_name = self._storeize(ld_name)
  File "hy/compiler.py", line 607, in _storeize
    new_elts.append(self._storeize(x, func))
  File "hy/compiler.py", line 616, in _storeize
    raise TypeError("Can't assign / delete a %s object" % type(name))
```

Now:

```
  File "x.hy", line 1, column 7

  (setv [1 2] 1)
        ^---^
HyTypeError: Can't assign / delete a HyList
```

### CODE REVIEW

**Comment by berkerpeksag** [comment]
LGTM.

Two minor suggestions:

1. I'd tweak the exception message from `... assign / delete ...` to `... assign or delete ...`
2. It would be nice to add a small test for this

Thanks!

**Comment by kirbyfan64** [comment]
@berkerpeksag Done!

**Comment by berkerpeksag** [comment]
flake8 looks unhappy :)

```
hy/compiler.py:1354:80: E501 line too long (80 > 79 characters)
```

Can you fix that and squash your commits?

**Comment by kirbyfan64** [comment]
@berkerpeksag Done.

**Comment by algernon** [comment]
Looks good! The git history is a bit funky (I have an idea or two why, I'll drop by on IRC tomorrow and explain, if anyone's interested), but that's no big deal.

:+1:

**Comment by kirbyfan64** [comment]
@algernon 

> I'll drop by on IRC tomorrow and explain, if anyone's interested

I am, but I don't hang out on IRC. :(

**Comment by algernon** [comment]
Ah, no worries. I'll just dump the ideas here then. :)

**Comment by kirbyfan64** [comment]
Bump?

**Comment by zackmdavis** [comment]
:shipit: On master as 283111b49 (I rebased locally to get rid of the duplicate of 0a942a069 that somehow slipped in to the branch that this pull request is from).

**Pull request closed without merging**
