### PR TITLE
Require capitalizing NaN and Inf like so

### LINKED ISSUE #1288: Any capitalization of "nan" or "inf" is interpreted as a float, not a symbol
For example:

    => (setv Nan 5)
      File "<input>", line 1, column 7

      (setv Nan 5)
            ^--^
    HyTypeError: b"Can't assign or delete a HyFloat"

The fact that Hy accepts literals for floating-point infinity and NaN, albeit unintentional, is a nice feature that we might as well keep. But, Hy ought to recognize only one capitalization.

### PR DESCRIPTION
**Pull request by Kodiologist**
Fixed #1288.

### CODE REVIEW

**Comment by gilch** [comment]
I would also prefer one canonical capitalization, but I'm more inclined to use all-lowercase `nan` and `inf`, since that is the Python repr.
```
>>> float('NaN')
nan
>>> float('Inf')
inf
```

**Comment by Kodiologist** [comment]
I noticed that, but I figured that starting with a capital letter is better for symmetry with `False`, `True`, and `None`, and the meaning of `NaN` is clearer when written in CamelCase.

Also, I'm not 100% sure that the Python `repr` is platform-independent.

**Comment by tuturto** [comment]
For what it's worth, I get all lowercase inf and nan when doing ```float('NaN')``` on my Windows 10 machine or Linux machine, on both Python 2.x and 3.x. That said, I kind of like ```NaN``` nicer looking than ```nan```.

I would be inclined to choose ```NaN``` and ```Inf```` over ```nan``` and ```inf````, but I don't feel about this particularly strongly.

**Comment by gilch** [comment]
I'm not sure what to think. I guess my feelings are not that strong either. @kirbyfan64, what say you?

**Comment by kirbyfan64** [comment]
My only question is whether or not it's actually *worthwhile* to add so much extra code just to check the inf and NaN capitalization...

**Comment by Kodiologist** [comment]
I'm all for concise implementation, but surely you don't mean to suggest that we should interpret all of `Nan`, `nan`, `nAN`, etc. as the special floating-point value, in defiance of the case-sensitivity of the rest of the language, do you? Surely a bunch of code is a reasonable price to pay for avoiding that.

**Comment by Kodiologist** [comment]
C'mon, guys, nothing will happen if you don't make any decisions.

**Comment by kirbyfan64** [comment]
@Kodiologist can you rebase this?

**Pull request merged**
