### PR TITLE
Add `...` as special syntax for Ellipsis

### LINKED ISSUE #2143: Allow `...` as shorthand for `Ellipsis` as in Python

### PR DESCRIPTION
**Pull request by Kodiologist**
Closes #2143.

### CODE REVIEW

**Comment by allison-casey** [comment]
Neat! Will review this when I get home tonight

**Comment by allison-casey** [comment]
so everything seems good. I am curious how this will affect #2096 will we just have to special case three `.`s in the reader or something?

**Comment by scauligi** [comment]
I was going to raise that point as well; it might make more sense to implement this directly in the reader?

**Comment by Kodiologist** [comment]
Yes, I think the implementation will have to change to support that, and `...` will probably have to be special-cased in the reader. Fortunately, the current implementation is very simple, so very little will be lost.

**Review by allison-casey — APPROVED** [review]

**Review by scauligi — APPROVED** [review]

**Pull request merged**
