### PR TITLE
Support Python 3.10

### PR DESCRIPTION
**Pull request by Kodiologist**
Let's see which release Travis is running, if it supports it at all.

### CODE REVIEW

**Comment by Kodiologist** [comment]
@allison-casey `pprint._safe_repr` is gone, which breaks `pprint`. Ideas?

**Comment by allison-casey** [comment]
I'd have to see why, let me take a look

**Comment by scauligi** [comment]
Ah, I was sitting on a patch from when I was testing 3.10 for builtins, still hadn't gotten around to cleaning it up.

This should fix pprint:
```diff
diff --git a/hy/contrib/pprint.hy b/hy/contrib/pprint.hy
index b5930602..850f5b80 100644
--- a/hy/contrib/pprint.hy
+++ b/hy/contrib/pprint.hy
@@ -29,12 +29,16 @@ The differences that do exist are as follows:
         re
         collections
         [pprint [PrettyPrinter :as PyPrettyPrinter
-                 -safe-repr :as -safe-py-repr
                  -recursion
                  -safe-tuple
                  -safe-key]]
         [hy.contrib [hy-repr]]
-        [hy.-compat [PY38]])
+        [hy.-compat [PY38 PY310]])
+
+(if PY310
+  (defn -safe-py-repr [object context maxlevels level sort-dicts]
+    (.-safe-repr (PyPrettyPrinter :sort-dicts sort-dicts) object context maxlevels level))
+  (import [pprint [-safe-repr :as -safe-py-repr]]))
 
 (setv --all-- ["pprint" "pformat" "saferepr" "PrettyPrinter" "is_readable" "is_recursive" "pp"])
```

**Comment by Kodiologist** [comment]
Nice, I'll try that.

**Comment by allison-casey** [comment]
Scauligi to the rescue!

**Pull request merged**
