### PR TITLE
added defmacro!

### PR DESCRIPTION
**Pull request by gilch**
I saw `defmacro/g!` in _Let Over Lambda_ before I saw it in Hy, but it's just a helper macro for the real utility: `defmacro!`, which is like `defmacro/g!`, plus automatic once-only evaluation for
`o!` parameters, which are available as the equivalent `g!` symbol. This pull translates `defmacro!` to Hy.

For those who haven't read the book, a common problem with macros is multiple-evaluation.

``` Hy
=> (defn expensive-get-number [] (print "spam") 14)
=> (defmacro triple-1 [n] `(+ n n n))
=> (triple-1 (expensive-get-number))  ; evals n three times!
spam
spam
spam
42
```

You can avoid this with a gensym:

``` Hy
=> (defmacro/g! triple-2 [n] `(do (setv ~g!n ~n) (+ ~g!n ~g!n ~g!n)))
=> (triple-2 (expensive-get-number))  ; avoid repeats with a gensym
spam
42
```

But this is more concise and clear with `defmacro!`, which does that for you:

``` Hy
=> (defmacro! triple-3 [o!n] `(+ ~g!n ~g!n ~g!n))
=> (triple-3 (expensive-get-number))  ; easier with defmacro!
spam
42
```

### CODE REVIEW

**Comment by gilch** [comment]
I saw #902. This looks like a better fix for `setv` than what I have here. It should be an easy merge.

**Comment by algernon** [comment]
This looks interesting, will take a look in a bit.

**Comment by algernon** [comment]
Well, that "bit" took a bit long, but I like this, :+1:

**Comment by tuturto** [comment]
Looks really nifty, took me a while to understand what's going on here. But while testing, I get this error:

```hy
(hy)tuukka@azrael:~/programming/hy$ hy
hy 0.11.0 using CPython(default) 3.4.0 on Linux
=> (defn expensive-get-number [] (print "spam") 14)
=> (defmacro! triple-3 [o!n] `(+ ~g!n ~g!n ~g!n))
=> (triple-3 (expensive-get-number))
  File "<input>", line 1, column 1

  (triple-3 (expensive-get-number))
  ^-------------------------------^
HyMacroExpansionError: expanding `triple_3': unsupported callable
```

I haven't yet looked deeper into this, so I don't know how obvious this is.

**Comment by gilch** [comment]
I think it's just you.
```Python
hy 0.11.0 using CPython(v3.4.3:9b73f1c3e601) 3.4.3 on Windows
=> (defn expensive-get-number [] (print "spam") 14)
def expensive_get_number():
    print('spam')
    return 14
=> (defmacro! triple-3 [o!n] `(+ ~g!n ~g!n ~g!n))
from hy.core.language import gensym, interleave
import hy
from hy import HyExpression, HySymbol

@hy.macros.macro('triple_3')
def _hy_anon_fn_2(o!n):

    def _hy_anon_fn_1():
        g!n = gensym(HySymbol('g!n')[2:])
        return HyExpression(((([] + [HySymbol('do')]) + [HyExpression((([] + [HySymbol('setv')]) + list(interleave([g!n], [o!n]))))]) + list([HyExpression((((([] + [HySymbol('+')]) + [g!n]) + [g!n]) + [g!n]))])))
    return _hy_anon_fn_1()
=> (triple-3 (expensive-get-number))
:n_1235 = expensive_get_number()
((:n_1235 + :n_1235) + :n_1235)
spam
42
=> (macroexpand '(triple-3 (expensive-get-number)))
from hy.core.language import macroexpand
from hy import HyExpression, HySymbol
macroexpand(HyExpression((([] + [HySymbol('triple_3')]) + [HyExpression(([] + [HySymbol('expensive_get_number')]))])))
('do' ('setv' ':n_1236' ('expensive_get_number')) ('+' ':n_1236' ':n_1236' ':n_1236'))
```
```Hy
;; the macroexpand with manual pretty-printing
(do (setv :n_1236 (expensive_get_number))
    (+ :n_1236 :n_1236 :n_1 236))
```
The Travis CI build passed.
Try uninstalling Hy altogether before re-installing this branch in your virtual environment. Or create a new virtual environment without Hy in it, then install just this branch it should work.

**Comment by tuturto** [comment]
This is funky. I created completely new virtualenv, cloned hy and installed this branch. Still getting the same error. But for you it obviously works and travis is happy too.

**Comment by kirbyfan64** [comment]
What version of Python do you have?

**Comment by tuturto** [comment]
hy 0.11.0 using CPython(default) 3.4.3 on Linux

**Comment by gilch** [comment]
tuturto said:
> hy 0.11.0 using CPython(default) 3.4.0 on Linux

I said:
> hy 0.11.0 using CPython(v3.4.3:9b73f1c3e601) 3.4.3 on Windows

Clearly, *something* about our setup differs.

**Comment by tuturto** [comment]
is ```pip install -e .``` still the correct way to install editable version?

**Comment by gilch** [comment]
We have `tox` to test against multiple Python versions. I think Travis does this too.

**Comment by gilch** [comment]
@tuturto I installed it using `pip install -e .` from the repository's root folder, and it worked for me.

**Comment by gilch** [comment]
Make sure you have no Hy installed outside of a virtualenv.

**Comment by tuturto** [comment]
I checked and there's no Hy installed outside of the virtualenv. Tox fails with the same error message. I can try blank virtual machine tomorrow to see if there's something wrong with settings of the one I'm using.

**Comment by gilch** [comment]
Try `hy --spy` and see if there's anything wrong with the Python output.

**Comment by tuturto** [comment]
Looks similar to me:
```
(hy)tuukka@azrael:~/programming/hy$ hy --spy
hy 0.11.0 using CPython(default) 3.4.3 on Linux
=> (defn expensive-get-number [] (print "spam") 14)
def expensive_get_number():
    print('spam')
    return 14
=> (defmacro! triple-3 [o!n] `(+ ~g!n ~g!n ~g!n))
import hy
from hy import HyExpression, HySymbol
from hy.core.language import gensym, interleave

@hy.macros.macro('triple_3')
def _hy_anon_fn_2(o!n):

    def _hy_anon_fn_1():
        g!n = gensym(HySymbol('g!n')[2:])
        return HyExpression(((([] + [HySymbol('do')]) + [HyExpression((([] + [HySymbol('setv')]) + list(interleave([g!n], [o!n]))))]) + list([HyExpression((((([] + [HySymbol('+')]) + [g!n]) + [g!n]) + [g!n]))])))
    return _hy_anon_fn_1()
=> (triple-3 (expensive-get-number))
  File "<input>", line 1, column 1

  (triple-3 (expensive-get-number))
  ^-------------------------------^
HyMacroExpansionError: expanding `triple_3': unsupported callable
```
It doesn't seem to like the ```triple_3``` decorator.

**Comment by gilch** [comment]
Very strange. I wonder if the other macros are affected on your setup. Does `defmacro/g!` work for you? Also try entering the `(defmacro defmacro! ...)` code at the `hy --spy` repl using the master branch, and see if that functions.

**Comment by gilch** [comment]
You should be able to use `pip install git+https://github.com/gilch/hy.git@defmacro!` to install this branch directly from github. It should rule out any corruption of your local repository.

**Comment by tuturto** [comment]
triple-2 code works without problems for me and tests pass for everything else but this. Defining defmacro! in repl using master branch gives me the same error. Local repository is freshy cloned, but I'll give it another go.

**Comment by tuturto** [comment]
Ha, installing directly from your repository worked. That narrows it down nicely.

**Comment by kirbyfan64** [comment]
Try deleting your folder containing Hy and re-cloning it.

**Comment by tuturto** [comment]
Already tried that earlier without luck, when I was testing clean virtualenv.

**Comment by tuturto** [comment]
@kirbyfan64 this PR works for you, right?

**Comment by tuturto** [comment]
Because if I do:
```
git checkout 649dd38040378bd32c42cf0e33b400a42b2b44b8 -b baz
git pull https://github.com/gilch/hy.git defmacro!
pip install -e .
```
The defmacro! works without a hitch. Is it possible that one of the changes that has been done to master since this PR has been created has broken this? Travis is only run when PR is created and not for every subsequent change to master?

**Comment by gilch** [comment]
I updated a local defmacro! branch with the latest hylang/master. I can confirm the same error.
```Python
hy 0.11.0 using CPython(v3.4.3:9b73f1c3e601) 3.4.3 on Windows
=> (defmacro! triple-3 [o!n] `(+ ~g!n ~g!n ~g!n))
from hy.core.language import gensym, interleave
import hy
from hy import HyExpression, HySymbol

@hy.macros.macro('triple_3')
def _hy_anon_fn_2(o!n):

    def _hy_anon_fn_1():
        g!n = gensym(HySymbol('g!n')[2:])
        return HyExpression(((([] + [HySymbol('do')]) + [HyExpression((([] + [Hy
Symbol('setv')]) + list(interleave([g!n], [o!n]))))]) + list([HyExpression((((([
] + [HySymbol('+')]) + [g!n]) + [g!n]) + [g!n]))])))
    return _hy_anon_fn_1()
=> (triple-3 3)
  File "<input>", line 1, column 1

  (triple-3 3)
  ^----------^
HyMacroExpansionError: expanding `triple_3': unsupported callable
```
It does appear that a recent change to master has broken this. Since it was working before, I don't think the error is in my code (at least not my code from this branch; some of the recent PRs were mine). This means that a recent change in Hy has not been tested adequately. We should isolate this bug before it causes further problems.

**Comment by kirbyfan64** [comment]
On Python 2, the error is:

```
Traceback (most recent call last):
  File "hy/compiler.py", line 2529, in hy_compile
    result = compiler.compile(tree)
  File "hy/compiler.py", line 432, in compile
    ret = self.compile_atom(_type, tree)
  File "hy/compiler.py", line 424, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "hy/compiler.py", line 623, in compile_raw_list
    ret = self._compile_branch(entries)
  File "hy/compiler.py", line 488, in _compile_branch
    return _branch(self.compile(expr) for expr in exprs)
  File "hy/compiler.py", line 316, in _branch
    results = list(results)
  File "hy/compiler.py", line 488, in <genexpr>
    return _branch(self.compile(expr) for expr in exprs)
  File "hy/compiler.py", line 444, in compile
    raise_empty(HyCompileError, e, sys.exc_info()[2])
  File "hy/_compat.py", line 66, in raise_empty
    raise t(*args)
HyCompileError: Internal Compiler Bug 😱
⤷ SyntaxError: invalid syntax (<string>, line 1)
Compilation traceback:
File "hy/compiler.py", line 432, in compile
    ret = self.compile_atom(_type, tree)
  File "hy/compiler.py", line 424, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "hy/compiler.py", line 1935, in compile_expression
    expression = macroexpand(expression, self.module_name)
  File "hy/macros.py", line 147, in macroexpand
    tree = macroexpand_1(tree, module_name)
  File "hy/macros.py", line 170, in macroexpand_1
    m_copy = make_emtpy_fn_copy(m)
  File "hy/macros.py", line 132, in make_emtpy_fn_copy
    empty_fn = eval(fn_str)
```

**Comment by kirbyfan64** [comment]
Found out the issue:

```
ryan@DevPC-LX:~/stuff/hyg$ git bisect bad
f18007955dfa5fe294883159a4b7835bb2aa2252 is the first bad commit
commit f18007955dfa5fe294883159a4b7835bb2aa2252
Author: Adam Schwalm <adamschwalm@gmail.com>
Date:   Sun Aug 30 13:14:16 2015 -0500

    Better error messages on invalid macro arguments

:040000 040000 2e790e21a05e3bee2c469bf5fb692ee29c883f66 d6d9afab796071735ad03b8a582380161a38fffd M	hy
:040000 040000 d54507c2031419361d99c258395d8bd4f28cbfbb c1ba372f55127e1014b444ea8b58ec7633d64704 M	tests
ryan@DevPC-LX:~/stuff/hyg$ 
```

**Comment by kirbyfan64** [comment]
https://github.com/hylang/hy/commit/f18007955dfa5fe294883159a4b7835bb2aa2252

**Comment by gilch** [comment]
Is that the error check from #924?

**Comment by kirbyfan64** [comment]
@gilch Yup.

**Comment by kirbyfan64** [comment]
Got a working patch. Opening a PR...

**Comment by gilch** [comment]
It's `eval`ing a string. But Hy AST isn't always valid Python. I wonder if we could rewrite this to generate the lambda using AST instead of using a string.

**Comment by kirbyfan64** [comment]
@gilch It's not the string that's the issue. `getargspec` doesn't like the callable it's being passed.

**Comment by kirbyfan64** [comment]
@gilch #956

**Comment by paultag** [comment]
Good holy hot damn. This is amazing teamwork and a really model PR. Nice
work, team.

💖💖💖💖💖

**Comment by paultag** [comment]
LGTM! RFR, someone give this a last ack and merge, @hylang/core!

**Comment by gilch** [comment]
I don't think we can merge this before #989 gets resolved. All checks passed at the time, but I'm not confident they'll still work after #924 broke it. I think we can have Travis re-check this if I close it and re-open.

**Comment by gilch** [comment]
@hylang/core, failed as expected. LGTM is premature. I propose reverting #924, since our attempts to save it have not worked well.

**Comment by kirbyfan64** [comment]
@gilch Does #989 fix it? If so, I can try rebasing it and getting it ready to merge again (even though I never figured out what was really going on...).

**Comment by gilch** [comment]
Rebased on #1114 and it's still not working. Either I did the merge wrong or something else has changed.

**Comment by Kodiologist** [comment]
Do you want to keep this PR open, Gilch?

**Comment by gilch** [comment]
@Kodiologist, yes, it was working before. I don't think there's anything wrong with this PR, but there's a bug in Hy we still haven't fixed.

**Comment by tuturto** [comment]
I poked this with a stick a bit. Funny thing is that at least in Python 3.5 ``getfullargspec`` catched all exceptions and raises ``TypeError`` instead. By putting ``try``-``except`` around ``getargspec`` call and printing out ``__cause__`` magic attribute, we get: "'o!n' is not a valid parameter name". So I guess that's the problem (part of it at least) and we need to mangle the 'o!n' or something?

**Comment by tuturto** [comment]
```
=> (defn expensive-get-number [] (print "spam") 14)
=> (defmacro! triple-3 [o!n] `(+ ~g!n ~g!n ~g!n))
=> (triple-3 (expensive-get-number))
spam
42
=>
```
No clue what else I just broke though. Tests pass, so I guess it's ok until proven otherwise. There's "working" code at tuturto@6f37499d39e95

**Comment by tuturto** [comment]
After poking this a bit more, I have to conclude that there's no way that I could fix this. Might actually be that there's no way in general to fix this as long as we want to have that ``getargspec``call there. o!n isn't valid parameter name in Python and that's the root cause.

@gilch and (@hylang/core in general) have a look at [merge+hack for #903](/tuturto/hy/tree/nugget), containing tuturto@6f37499d39e959b and tuturto@108e2aef4ce5a6. Maybe we could work around the issue like this for the time being?

**Comment by gilch** [comment]
closed by #1172

**Pull request closed without merging**
