### PR TITLE
Adapt attribute completion from IPython completer 

### PR DESCRIPTION
**Pull request by icholy**
Recreating #754 because I can't reopen it after squashing.

### CODE REVIEW

**Comment by icholy** [comment]
@berkerpeksag I think it's ready.

**Comment by Foxboron** [comment]
Rad!
I do find those empty `except` statements annoying but thats the only nitpick i got.

:shipit:

**Comment by berkerpeksag** [comment]
Yeah, could you replace them with `except Exception`?

**Comment by icholy** [comment]
@berkerpeksag @Foxboron done

**Comment by berkerpeksag** [comment]
Thanks!

**Pull request merged**
