### PR TITLE
ignore PyCharm .idea/

### PR DESCRIPTION
**Pull request by gilch**
This is a hidden folder that PyCharm (or IntelliJ with equivalent plugin) uses for bookkeeping. An IDE like PyCharm can make some aspects of managing bigger Python projects (like Hy) easier to deal with, but I don't think it belongs in the repository.

### CODE REVIEW

**Comment by gilch** [comment]
😕 why is flake8 complaining about .gitignore?

**Comment by Kodiologist** [comment]
It isn't. It's complaining about a bunch of files you didn't change, as in #1152.

**Comment by berkerpeksag** [comment]
I think user-specific values should go into your global .gitignore file. I'd like to keep the scope of .gitignore small and only cover things that are specific to hylang project itself.

**Comment by Kodiologist** [comment]
I agree. The tracked `.gitignore` should be for files related to the project's own toolchain. Individual developers can ignore files that their own tools generate by using `.git/info/exclude`.

**Pull request closed without merging**
