### PR TITLE
Add versioned entry point scripts

### LINKED ISSUE #931: Multiple implementations overwrite each others' entrypoint hooks
It's not uncommon to find Python 2 and Python 3 coexisting on the same system, and it's not unreasonable for the user to also want Hy for both Pythons. However, where Python handles this gracefully by providing separate executables (`python2` and `python3` alongside `python`, `pip2` and `pip3` alongside `pip` etc) Hy simply bulldozes an existing `hy`, `hyc` etc.

Sorry if this has already been reported; I tried to look for previous issues but nothing much came to mind when I was trying to play guess-the-keyword.

### PR DESCRIPTION
**Pull request by kirbyfan64**
Haha, I'm good at doing this quickly. :)

Closes #931. @Ketsuban Looks good?

### CODE REVIEW

**Comment by Ketsuban** [comment]
For some reason I expected this to be harder or I'd have taken a look at doing it myself. I guess I forgot `setup.py` is still Python source so you can play tricks like that.

Looks good to me. You might consider also adding variants which use both the major and minor components of the version_info tuple (e.g. `hy-2.7`) since `easy_install` and `pip` do that, but it's probably overkill.

**Comment by Foxboron** [comment]
I'll just be blunt and shoot this down.

This isn't a hy problem. The reason why you have `python2` and `python3` is because python offer two versions, and they have been packaged for this. This isn't handled by Python itself, its handled by the package to your distro. Hy isn't suppose to care, and if you want hy to care, you churn out a virtualenv.

I really struggle to see why this should be fixed in the Hy source.

**Comment by Ketsuban** [comment]
`python2` and `python3` are *created* by distro packaging, sure, but their existence is due to distros obeying the relevant PEP. In any case, I didn't install Hy with a distro package—I installed it with pip.

**Comment by kirbyfan64** [comment]
Doesn't IPython also do this? I have an `ipython3` on my computer.

I have to like this idea. It seems fine but gets REALLY irritating when you need to run Hy with the separate Python versions. I have both 2 and 3 (Anaconda) installed, so I tend to greatly appreciate the projects that care of this for me. :)

**Comment by kirbyfan64** [comment]
(BTW, has anybody else noticed that I tend to do the PRs that are insanely controversial?? :D )

**Comment by algernon** [comment]
I'd be fine with allowing the user to specify what postfix to append to the binaries installed by hy. I may have python3.2 and python3.4 installed at the same time, and the current patch won't handle that. Since this is a distro thing, if Hy makes it easy to change the script names, that's fine. But trying to do that automatically is not something we should do, in my opinion.

**Comment by berkerpeksag** [comment]
Yes, ipython, pip and others do the same thing. Patch LGTM.

**Comment by Foxboron** [comment]
CC: @paultag on this.

**Comment by kirbyfan64** [comment]
Bump?

**Comment by Kodiologist** [comment]
@berkerpeksag approved this and so do I, so that's two, so I'm merging, even if we're a few months too late for this pull request's one-year anniversary. It's a very small change and has obvious utility. That said, I'm still happy to consider any PRs for alternative approaches to the same problem, such as @algernon's suggestion.

**Pull request merged**
