### PR TITLE
Document more gotchas

### LINKED ISSUE #1324: .pyc files don't get recreated when they use a macro from a file that was changed
It seems like Hy is using the .pyc cache even if the file we're loading has a newer filesystem mtime than the .pyc file -- Python will default to overwriting the pyc.

This winds up biting people who update a script and wind up very confused about why something isn't being invoked :)

(Just bit me on the version on pypi - anyone know if this is being tracked with another issue?)

### LINKED ISSUE #1342: Arguments aren't always evaluated left to right
For example,
```Python
=> (setv foo 42)
foo = 42
None
=> [foo (del foo)]
del foo
[foo, None]
Traceback (most recent call last):
  File "c:\users\me\documents\github\hy\hy\importer.py", line 198, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'foo' is not defined
```
The expected result was `[42, None]`.

### PR DESCRIPTION
**Pull request by Kodiologist**
- Closes #1324
- Closes #1342

### CODE REVIEW

**Comment by Kodiologist** [comment]
I wouldn't recommend that. It doesn't save the user from having to understand the underlying phenomenon, so long as they're still using bytecode at all.

**Comment by scauligi** [comment]
> so long as they're still using bytecode at all.

You mean if they're running `.pyc` files directly instead of just implicitly via the pycache? Because in the typical pycache case I have some code in the importer that can check the (tree of) macro dependencies and recompile (that is, consider the cached `.pyc` invalid) if any of the dependencies are themselves stale.

To me this feels seems to give a more intuitive experience, e.g. if you edit a file that exports macros then try to re-run a dependee script.

**Comment by Kodiologist** [comment]
> > so long as they're still using bytecode at all.
>
> You mean if they're running `.pyc` files directly instead of just implicitly via the pycache?

Just implicitly.

I get that dependency-tracking can work in many common cases, but I don't think it's fully general; thus, "it doesn't save the user from having to understand the underlying phenomenon, so long as they're still using bytecode at all".

**Comment by Kodiologist** [comment]
@scauligi Any objections to merging this?

**Comment by scauligi** [comment]
Ah nope, no objections

**Pull request merged**
