### PR TITLE
Add missing core member

### PR DESCRIPTION
**Pull request by brandonwillard**

### CODE REVIEW

**Comment by Kodiologist** [comment]
I'd say we should probably just delete this list. It's redundant with the list kept by GitHub itself, so it's just another thing we can forget to update, as I did in your case.

**Comment by brandonwillard** [comment]
Replace it with a link to [Hy Society members](https://github.com/orgs/hylang/people)?

**Comment by Kodiologist** [comment]
That makes sense. Just link to the core team (https://github.com/orgs/hylang/teams/core) specifically.

**Comment by tianon** [comment]
FYI, https://github.com/orgs/hylang/teams/core/members is a 404 for nonmembers.

**Comment by Kodiologist** [comment]
@tianon That should be fixed now. I think it was marked as a "secret" team.

**Comment by brandonwillard** [comment]
Ohh, now I kind of like the idea of it being a secret (Hy) society.

**Comment by tianon** [comment]
I'd suggest testing incognito (it still 404s for me).

**Comment by Kodiologist** [comment]
It seems that GitHub won't even let you see a list of teams without logging in. So now I see the value of `coreteam.rst`.

Brandon, could you edit the whole list so that `coreteam.rst` matches https://github.com/orgs/hylang/teams/core/members (e.g., @gilch is also missing from `coreteam.rst`), preferably in the same order? Then I'll merge this.

**Comment by Kodiologist** [comment]
Superseded by #1783.

**Pull request closed without merging**
